required_vars="SSH_USERNAME SSH_SERVER_ADDRESS SSH_INTERNAL_ADDRESS SSH_SERVER_PORT SSH_PRIVATE_KEY TF_TOKEN_app_terraform_io HOSTNAME TF_CLOUD_ORGANIZATION KUBECONFIG PAT_GITHUB_TOKEN RENOVATE_TOKEN KUBECONFIG_CONTENT ARGOCD_DEPLOY_PRIVATE_KEY ARGOCD_REPO_NAME INTERNAL_IP EXTERNAL_IP KUBERNETES_VERSION STORAGE"

for var in $required_vars; do
  if [ -z "$(eval echo \$$var)" ]; then
    echo "❌ Required secret/env var $var is not set!"
    exit 1
  fi
done