services:
  enso-homelab:
    container_name: enso-homelab
    build:
      context: .
      dockerfile: ./deploy/docker/Dockerfile.dev
    restart: "no"
    #env_file: .env
    networks:
      - enso-homelab-network
    volumes:
      #- ${HOME}/.config/gh:/home/enso/.config/gh
      - ./deploy:/home/enso/enso-homelab/deploy
      - ${HOME}/.ssh/id_ed25519:/home/enso/.ssh/id_ed25519:ro
      # - ${HOME}/.zhistory:/home/enso/.zhistory
      # - ${HOME}/.zshrc:/home/enso/.zshrc
      - ./:/home/enso/enso-homelab
      #- /var/run/docker.sock:/var/run/docker.sock
      #- /home/loeken/.terraform.d/:/home/enso/.terraform.d/

networks:
  enso-homelab-network:
    driver: bridge
