---
apiVersion: upgrade.cattle.io/v1
kind: Plan
metadata:
  name: k3s-agent
  namespace: kube-system
spec:
  concurrency: {{ .Values.concurrency }}
  nodeSelector:
    matchExpressions:
      - key: node-role.kubernetes.io/control-plane
        operator: DoesNotExist
  serviceAccountName: system-upgrade
  prepare:
    image: rancher/k3s-upgrade
    args:
      - prepare
      - k3s-server
  upgrade:
    image: rancher/k3s-upgrade
  version: {{ .Values.k3sVersion }}
  drain:
    force: {{ .Values.drain.force }}
    skipWaitForDeleteTimeout: {{ .Values.drain.skipWaitForDeleteTimeout }}
