FROM golang:1.24-alpine@sha256:43c094ad24b6ac0546c62193baeb3e6e49ce14d3250845d166c77c25f64b0386

# Set working directory
WORKDIR /home/enso/enso-homelab

# Install required packages
RUN apk add --no-cache \
    bash \
    sudo \
    curl \
    git \
    openssh \
    py3-pip \
    python3 \
    ansible \
    jq \
    make \
    docker-cli \
    coreutils \
    tzdata \
    libc6-compat \
    less \
    vim \
    zsh \
    nodejs \
    npm \
    nano

# Install Terraform manually from HashiCorp
RUN git clone https://github.com/tfutils/tfenv.git ~/.tfenv \
 && ln -s ~/.tfenv/bin/* /usr/local/bin \
 && tfenv install

# Create non-root user "enso" with passwordless sudo
RUN adduser -D enso && echo "enso ALL=(ALL) NOPASSWD:ALL" > /etc/sudoers.d/enso

# Ensure working directory exists and is owned by "enso"
RUN mkdir -p $GOPATH /home/enso/enso-homelab && chown -R enso:enso $GOPATH /home/enso/enso-homelab

# Set up zsh as default shell
RUN sed -i 's#/bin/sh#/bin/zsh#g' /etc/passwd

# Install Renovate globally via npm
RUN npm install -g renovate

USER enso

RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" && \
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git /home/enso/.oh-my-zsh/custom/themes/powerlevel10k && \
    git clone https://github.com/zsh-users/zsh-autosuggestions /home/enso/.oh-my-zsh/custom/plugins/zsh-autosuggestions && \
    git clone https://github.com/zsh-users/zsh-syntax-highlighting /home/enso/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

# Set GOPATH and update PATH
ENV HOME="/home/enso"
ENV GOPATH="$HOME/go"
ENV PATH="$GOPATH/bin:$PATH"
ENV EDITOR=nano

# copy default .zshrc to load plugins installed above
COPY deploy/docker/.zshrc /home/enso/.zshrc

# Default command for devcontainer to stay alive
CMD ["tail", "-f", "/dev/null"]