FROM golang:1.24-alpine@sha256:48ee313931980110b5a91bbe04abdf640b9a67ca5dea3a620f01bacf50593396

# Set working directory
WORKDIR /home/devcontainer

# Install required packages
RUN apk add --no-cache \
    bash \
    sudo \
    curl \
    git \
    openssh \
    py3-pip \
    python3 \
    ansible \
    jq \
    make \
    docker-cli \
    coreutils \
    tzdata \
    libc6-compat \
    less \
    vim \
    zsh \
    nodejs \
    npm \
    nano \
    gcc \
    linux-headers \
    python3-dev \
    musl-dev \
    py3-passlib

# Install passlib via pip to support Ansible's password hashing
RUN pip3 install --break-system-packages passlib

# Install GitHub CLI manually
RUN GH_ARCH="$(apk --print-arch | sed 's/x86_64/amd64/;s/aarch64/arm64/')" && \
    GH_VERSION=$(curl -s https://api.github.com/repos/cli/cli/releases/latest | grep tag_name | cut -d '"' -f 4) && \
    curl -L -o gh.tar.gz https://github.com/cli/cli/releases/download/${GH_VERSION}/gh_${GH_VERSION#v}_linux_${GH_ARCH}.tar.gz && \
    tar -xzf gh.tar.gz && \
    mv gh_*/bin/gh /usr/local/bin/ && \
    rm -rf gh.tar.gz gh_*

# Install k3sup
RUN cd /tmp && curl -sLS https://get.k3sup.dev | sh

# Install act
RUN curl -s https://raw.githubusercontent.com/nektos/act/master/install.sh | sudo bash

# Set up zsh as default shell
RUN sed -i 's#/bin/sh#/bin/zsh#g' /etc/passwd

# Install Renovate globally via npm
RUN npm install -g renovate

# Create a virtualenv for OpenStack CLI
RUN python3 -m venv /venv

# Install OpenStack CLI into venv
RUN . /venv/bin/activate && \
    pip install --upgrade pip && \
    pip install openstackclient

# Optional SSH folder
RUN mkdir -p /root/.ssh

# Set environment
ENV HOME="/root"
ENV GOPATH="$HOME/go"
ENV PATH="$GOPATH/bin:/venv/bin:$PATH"
ENV EDITOR=nano

# Install Terraform manually from HashiCorp
RUN git clone https://github.com/tfutils/tfenv.git ~/.tfenv \
 && ln -s ~/.tfenv/bin/* /usr/local/bin \
 && tfenv install

# Oh My Zsh + Powerlevel10k + plugins
RUN sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)" && \
    git clone --depth=1 https://github.com/romkatv/powerlevel10k.git ~/.oh-my-zsh/custom/themes/powerlevel10k && \
    git clone https://github.com/zsh-users/zsh-autosuggestions ~/.oh-my-zsh/custom/plugins/zsh-autosuggestions && \
    git clone https://github.com/zsh-users/zsh-syntax-highlighting ~/.oh-my-zsh/custom/plugins/zsh-syntax-highlighting

# Copy ZSH config
COPY deploy/docker/.zshrc /root/.zshrc

# Default command
CMD ["tail", "-f", "/dev/null"]
