---
- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true

- name: Install base packages
  ansible.builtin.apt:
    name:
      - btop
      - kubernetes-client
      - curl
    state: present

- name: Add noatime and nodiratime to ext4 mounts
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^(UUID=[\w-]+)\s+(/\S*)\s+(ext4)\s+(\S+)\s+(\d\s+\d)$'
    line: '\1 \2 \3 \4,noatime,nodiratime \5'
    backrefs: yes

- name: Set root password
  ansible.builtin.user:
    name: root
    password: "{{ root_password | password_hash('sha512') }}"

- name: Install curl
  ansible.builtin.apt:
    name: curl
    state: latest
    update_cache: true
    force_apt_get: true
