---
- name: Check system hostname matches expected
  ansible.builtin.command: hostname -f
  register: current_hostname

- name: Fail if hostname does not match inventory_hostname
  ansible.builtin.fail:
    msg: "Current hostname ({{ current_hostname.stdout }}) does not match expected ({{ inventory_hostname }})! Please set the correct hostname before running this playbook."
  when: current_hostname.stdout != inventory_hostname

- name: Disable Proxmox enterprise repo (if present)
  ansible.builtin.shell: |
    if [ -f /etc/apt/sources.list.d/pve-enterprise.list ]; then
      sed -i 's/^deb/#deb/' /etc/apt/sources.list.d/pve-enterprise.list
    fi
  changed_when: false

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true

- name: Install base packages
  ansible.builtin.apt:
    name:
      - btop
      - kubernetes-client
      - curl
      - gpg

- name: Add Proxmox apt GPG key
  ansible.builtin.apt_key:
    url: "https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg"
    state: present

- name: Update APT cache
  ansible.builtin.apt:
    update_cache: true

- name: Install base packages
  ansible.builtin.apt:
    name:
      - btop
      - kubernetes-client
      - curl
      - gpg
    state: present

- name: Add noatime and nodiratime to ext4 mounts
  ansible.builtin.lineinfile:
    path: /etc/fstab
    regexp: '^(UUID=[\w-]+)\s+(/\S*)\s+(ext4)\s+(\S+)\s+(\d\s+\d)$'
    line: '\1 \2 \3 \4,noatime,nodiratime \5'
    backrefs: yes

- name: Set root password
  ansible.builtin.user:
    name: root
    password: "{{ root_password | password_hash('sha512') }}"

- name: Install curl
  ansible.builtin.apt:
    name: curl
    state: latest
    update_cache: true
    force_apt_get: true

- name: Ensure /etc/hosts contains hostname mapping
  ansible.builtin.lineinfile:
    path: /etc/hosts
    regexp: "^127\\.0\\.1\\.1"
    line: "127.0.1.1 {{ inventory_hostname }} {{ inventory_hostname.split('.')[0] }}"
    state: present
