apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  project: default

  source:   # still required for legacy validation; must be dummy
    repoURL: ''
    path: '.'

  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 8.0.15
    - repoURL: git@github.com:loeken/enso-homelab-prod
      targetRevision: HEAD
      ref: values

  helm:
    valueFiles:
      - $values/deploy/helm/cluster_issuer/argocd-values.yaml

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
