apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  sources:
    - repoURL: https://argoproj.github.io/argo-helm
      chart: argo-cd
      targetRevision: 8.0.17
      helm:
        valueFiles:
          - $values/deploy/terraform/argocd/argocd-values.yaml
    # renovate: ignore
    - repoURL: git@github.com:loeken/{{ .Values.githubRepo  | default "enso-homelab" }}
      targetRevision: HEAD
      ref: values

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true