{{ if .Values.authelia.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: authelia
  namespace: argocd
spec:
  destination:
    namespace: authelia
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://charts.authelia.com
    targetRevision: 0.11.4
    chart: authelia
    helm:
      values: |
        image:
          repository: ghcr.io/authelia/authelia

        pod:
          replicas: {{ .Values.globalReplicaCount }}
          kind: StatefulSet
          revisionHistoryLimit: 2

            
        secret:
          disabled: false
          existingSecret: authelia
          mountPath: /secrets
          additionalSecrets:
            authelia:
              items:
                - key: identity_providers.oidc.jwks
                  path: identity_providers.oidc.jwks
                - key: identity_providers.oidc.issuer_private_key
                  path: identity_providers.oidc.issuer_private_key
                - key: session.encryption.key
                  path: session.encryption.key
                - key: storage.encryption.key
                  path: storage.encryption.key
                - key: oidc.sharedsecret.nextcloud
                  path: oidc.sharedsecret.nextcloud
                - key: oidc.sharedsecret.jellyfin
                  path: oidc.sharedsecret.jellyfin
                - key: oidc.sharedsecret.grafana
                  path: oidc.sharedsecret.grafana
                - key: oidc.sharedsecret.heimdallr
                  path: oidc.sharedsecret.heimdallr
                - key: notifier.smtp.password
                  path: notifier.smtp.password

        persistence:
          enabled: true
          storageClass: {{ .Values.authelia.storageClassName }}
          accessModes:
            - ReadWriteOnce
          size: {{ .Values.authelia.size }}

        ingress:
          enabled: {{ .Values.authelia.ingress.enabled }}
          className: "nginx"
          annotations:
            nginx.ingress.kubernetes.io/enable-cors: "true"
            nginx.ingress.kubernetes.io/cors-allow-origin: "https://heimdallr.{{ .Values.domain }}, http://localhost:8000"
            nginx.ingress.kubernetes.io/cors-allow-methods: "PUT, GET, POST, OPTIONS, DELETE, PATCH"
            nginx.ingress.kubernetes.io/cors-allow-headers: "authorization, content-type, accept, x-requested-with"
            nginx.ingress.kubernetes.io/cors-allow-credentials: "true"
            cert-manager.io/cluster-issuer: "{{ .Values.clusterIssuer }}"
            external-dns.alpha.kubernetes.io/hostname: "auth.{{ .Values.domain }}."
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
            external-dns.alpha.kubernetes.io/ttl: "120"
          rulesOverride:
            - host: auth.{{ .Values.domain }}
              path: /
          tls:
            enabled: true
            secret: auth-tls

        configMap:
          authentication_backend:
            password_reset:
              disable: true
          server:
            port: 9091
            path: ''
            asset_path: ''
            headers:
              csp_template: ''
          log:
            level: info
          theme: dark
          authentication_backend:
            file:
              enabled: true
          session:
            encryption_key:
              disabled: false
              secret_name: authelia
              path: session.encryption.key
            cookies:
              - domain: {{ .Values.domain }}
                name: authelia_sessions
                subdomain: auth
                expiration: 24h
                inactivity: 15m
          storage:
            encryption_key:
              disabled: false
              path: storage.encryption.key
            local:
              enabled: true
              path: /config/db.sqlite3
          notifier:
            filesystem:
              enabled: {{ .Values.authelia.filesystem.enabled }}
              filename: /config/notification.txt
            smtp:
              enabled: {{ .Values.authelia.smtp.enabled }}
              address: smtp://{{ .Values.authelia.smtp.host }}:{{ .Values.authelia.smtp.port }}
              username: {{ .Values.authelia.smtp.username }}
              password:
                disabled: false
                secret_name: authelia
                path: notifier.smtp.password
              sender: 'Authelia <{{ .Values.authelia.smtp.sender }}>'
              identifier: {{ .Values.authelia.smtp.host }}
              startup_check_address: {{ .Values.authelia.smtp.sender }}
              subject: "[Authelia] {title}"
              tls:
                server_name: {{ .Values.authelia.smtp.host }}
                skip_verify: false
                minimum_version: TLS1.2
          identity_providers:
            oidc:
              claims_policies:
                default:
                  id_token: ['rat', 'groups', 'email', 'email_verified', 'alt_emails', 'preferred_username', 'name']
              cors:
                allowed_origins:
                  - http://localhost:8000
                  - https://heimdallr.{{ .Values.domain }}
                allowed_origins_from_client_redirect_uris: true
              enabled: true
              jwks:
                - algorithm: RS256
                  key:
                    path: /secrets/authelia/identity_providers.oidc.jwks
              clients:
                - client_id: grafana
                  client_name: Grafana
                  client_secret:
                    path: /secrets/authelia/oidc.sharedsecret.grafana
                  public: false
                  authorization_policy: one_factor
                  redirect_uris:
                    - https://grafana.{{ .Values.domain }}/login/generic_oauth
                  scopes:
                    - openid
                    - profile
                    - groups
                    - email
                - client_id: nextcloud
                  client_name: NextCloud
                  client_secret:
                    path: /secrets/authelia/oidc.sharedsecret.nextcloud
                  public: false
                  authorization_policy: two_factor
                  require_pkce: true
                  pkce_challenge_method: S256
                  #claims_policy: nextcloud_userinfo
                  redirect_uris:
                    - https://nextcloud.{{ .Values.domain }}/apps/user_oidc/code
                  scopes:
                    - openid
                    - profile
                    - email
                    - groups
                  #  - 'nextcloud_userinfo'
                  userinfo_signed_response_alg: none
                  token_endpoint_auth_method: client_secret_post
                - client_id: heimdallr
                  client_name: Heimdallr
                  client_secret:
                    path: /secrets/authelia/oidc.sharedsecret.heimdallr
                  public: false
                  authorization_policy: "two_factor"
                  require_pkce: false
                  redirect_uris:
                    - https://heimdallr.{{ .Values.domain }}/auth/callback
                    - http://localhost:8000/auth/callback
                  scopes:
                    - openid
                    - profile
                    - email
                    - groups
                  response_types:
                    - code
                  grant_types:
                    - authorization_code
                  token_endpoint_auth_method: client_secret_post
                  claims_policy: default
                - client_id: jellyfin
                  client_name: Jellyfin
                  client_secret:
                    path: /secrets/authelia/oidc.sharedsecret.jellyfin
                  public: false
                  authorization_policy: one_factor
                  require_pkce: false
                  redirect_uris:
                    - https://jellyfin.{{ .Values.domain }}/sso/OID/redirect/authelia
                  scopes:
                    - openid
                    - profile
                    - email
                    - groups
                  response_types:
                    - code
                  grant_types:
                    - authorization_code
                  token_endpoint_auth_method: client_secret_post
          access_control:
            default_policy: deny
            rules:
              - domain: ['alertmanager.{{ .Values.domain }}', 'whoami.{{ .Values.domain }}', 'vaultwarden.{{ .Values.domain }}', 'prometheus.{{ .Values.domain }}','nextcloud.{{ .Values.domain }}','jellyfin.{{ .Values.domain }}','ha.{{ .Values.domain }}','alertmanager.{{ .Values.domain }}','grafana.{{ .Values.domain }}']
                policy: bypass
                headers:
                  - header: AuthChecker
                    pattern: '^{{ .Values.kumatoken }}$'
                methods:
                  - GET
                  - HEAD
              - domain: ['nextcloud.{{ .Values.domain }}']
                policy: bypass
                resources:
                  - ^/status.php$
                  - ^/index.php/login/v2$
                  - ^/index.php/login/v2/poll.*
                  - ^/login/v2/poll.*
                  - ^/index.php/core/wipe/check$
                  - ^/ocs/v2.php/apps/user_status/api/v1/heartbeat.*
                  - ^/ocs/v2.php/cloud/user$
                  - ^/ocs/v2.php/cloud/users/.*
                  - ^/apps/files/api/v1/stats$
                  - ^/ocs/v2.php/apps/notifications/api/v2/notifications.*
                  - ^/ocs/v2.php/apps/notifications/api/v2/push$
                  - ^/index.php/apps/files/preview-service-worker.js$
                  - ^/remote.php/dav/files/.*
                methods:
                  - GET
                  - POST
                  - PUT
                  - PROPFIND
              - domain: ['nextcloud.{{ .Values.domain }}']
                policy: two_factor
                subject:
                  - 'group:users'
              - domain: ['ha.{{ .Values.domain }}']
                policy: bypass
                resources:
                  - ^/api.*
                  - ^/auth/token.*
                  - ^/.external_auth=.
                  - ^/service_worker.js
                  - ^/static.*
                  - ^/local.*
                  - ^/hacsfiles.*
                  - ^/frontend_latest.*
              - domain: ['sonarr.{{ .Values.domain }}', 'radarr.{{ .Values.domain }}', 'ha.{{ .Values.domain }}']
                policy: bypass
                resources:
                  - ^/api.*
                  - ^/signalr.*
              - domain: ['vaultwarden.{{ .Values.domain }}']
                policy: bypass
                resources:
                  - ^/api/.*
                  - ^/identity/.*
                  - ^/notifications/.*
                  - ^/icons/.*
                  - ^/attachments/.*
                  - ^/events/.*
              - domain: 'rtorrent.{{ .Values.domain }}'
                policy: bypass
                resources:
                  - ^/RPC2.*
              - domain: ['requests.{{ .Values.domain }}']
                policy: bypass
                resources:
                  - ^/api/.*
                  - ^/auth/.*
                  - ^/webhook/.*
                methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
              - domain: ['status.{{ .Values.domain }}']
                policy: bypass
                resources:
                  - ^/api/.*
                  - ^/status/.*
                  - ^/metrics.*
                methods:
                  - GET
                  - POST
              - domain: ['jellyfin.{{ .Values.domain }}']
                policy: bypass
                resources:
                  - ^/sso/OID/.*
                  - ^/Auth/.*
                  - ^/api/.*
                  - ^/web/.*
                  - ^/Users/AuthenticateByName.*
                methods:
                  - GET
                  - POST
              - domain: ['ingestion.loeken.xyz']
                policy: bypass
                resources:
                  - ^/healthz$
                  - ^/api/.*
                  - ^/ingest$
                  - ^/status/.*
                  - ^/summaries/.*
                methods:
                  - GET
                  - POST
                  - PUT
                  - DELETE
                  - PATCH
              - domain: ['jellyfin.{{ .Values.domain }}', 'requests.{{ .Values.domain }}', 'hub.{{ .Values.domain }}', 'status.{{ .Values.domain }}', 'ai.{{ .Values.domain }}', 'ingestion.loeken.xyz']
                policy: one_factor
                subject:
                  - 'group:users'
              - domain: ['wazuh.{{ .Values.domain }}', 'alertmanager.{{ .Values.domain }}', 'prometheus.{{ .Values.domain }}', 'sinusbot.{{ .Values.domain }}', 'ha.{{ .Values.domain }}', 'prowlarr.{{ .Values.domain }}', 'sonarr.{{ .Values.domain }}', 'radarr.{{ .Values.domain }}', 'rtorrent.{{ .Values.domain }}', 'grafana.{{ .Values.domain }}', 'nzbget.{{ .Values.domain }}']
                policy: two_factor
                subject:
                  - 'group:admins'
              - domain: ['whoami.{{ .Values.domain }}', 'harbor.{{ .Values.domain }}', 'ltb-passwd.{{ .Values.domain }}', 'vaultwarden.{{ .Values.domain }}']
                policy: two_factor
                subject:
                  - 'group:users'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{ end }}