{{ if .Values.dashy.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dashy
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  project: default
  source:
    repoURL: 'https://github.com/vyrtualsynthese/selfhosted-helmcharts'
    targetRevision: HEAD
    path: charts/dashy
    helm:
      values: |
        replicaCount: 1
        image:
          repository: lissy93/dashy
          pullPolicy: IfNotPresent
        service:
          type: ClusterIP
          port: 8080
        ingress:
          enabled: {{ .Values.dashy.ingress.enabled }}
          className: "traefik"
          annotations:
            cert-manager.io/cluster-issuer: "{{ .Values.clusterIssuer }}"
            external-dns.alpha.kubernetes.io/hostname: "hubs.{{ .Values.domain }}."
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
            external-dns.alpha.kubernetes.io/ttl: "120"
            {{- if .Values.dashy.useAuthelia }}
            traefik.ingress.kubernetes.io/router.middlewares: default-authelia-forwardauth@kubernetescrd
            {{- end }}
          hosts:
            - host: hub.{{ .Values.domain }}
              paths:
                - path: /
                  pathType: Prefix
          tls:
            - secretName: dashy-tls
              hosts:
                - hub.{{ .Values.domain }}

        static:
          enabled: true
          configMapContent:
            conf: |-
              pageInfo:
                title: enso-homelab
                description: made with love in Berlin

              appConfig:
                theme: Adventure
                widgets:
                  - name: "K3s Cluster Monitoring - Panel 4"
                    type: iframe
                    options:
                      src: "https://grafana.{{ .Values.domain }}/d-solo/1815a1ab-3100-4c56-ab6c-c06345fac982/k3s-cluster-monitoring?orgId=1&from=now-30m&to=now&timezone=browser&var-Node=$__all&var-Namespace=$__all&refresh=1m&panelId=4"
                      height: 500
                      width: 100%

              sections:
                - name: Homelab
                  icon: fas fa-server
                  items:
                    - title: Authelia
                      description: Authentication gateway
                      url: https://auth.{{ .Values.domain }}
                      icon: fas fa-user-shield
                    - title: Fog Project
                      description: PXE server to capture image vms/servers
                      url: http://fog.{{ .Values.localDomain }}
                      icon: fas fa-bolt
                    - title: Vaultwarden
                      description: Password manager
                      url: https://vaultwarden.{{ .Values.domain }}
                      icon: fas fa-key
                    - title: Whoami
                      description: display headers
                      url: https://whoami.{{ .Values.domain }}
                      icon: fas fa-info-circle
                    - title: Home Assistant
                      description: Smart home control
                      url: https://ha.{{ .Values.domain }}
                      icon: fas fa-home
                - name: Media
                  icon: fas fa-photo-video
                  items:
                    - title: Jellyfin
                      description: Media server
                      url: https://jellyfin.{{ .Values.domain }}
                      icon: fas fa-film
                    - title: Jellyseerr
                      description: Media requests
                      url: https://requests.{{ .Values.domain }}
                      icon: fas fa-inbox
                    - title: NZBGet
                      description: Usenet downloader
                      url: https://nzbget.{{ .Values.domain }}
                      icon: fas fa-download
                    - title: Prowlarr
                      description: Indexer manager
                      url: https://prowlarr.{{ .Values.domain }}
                      icon: fas fa-search
                    - title: Radarr
                      description: Movie automation
                      url: https://radarr.{{ .Values.domain }}
                      icon: fas fa-video
                    - title: Sonarr
                      description: TV show automation
                      url: https://sonarr.{{ .Values.domain }}
                      icon: fas fa-tv
                    - title: SinusBot
                      description: TeamSpeak music bot
                      url: https://sinusbot.{{ .Values.domain }}
                      icon: fas fa-music
                - name: Observability
                  icon: fas fa-eye
                  items:
                    - title: Grafana
                      description: Metrics visualization platform
                      url: https://grafana.{{ .Values.domain }}
                      icon: fas fa-chart-line
                    - title: Prometheus
                      description: Metrics collection
                      url: https://prometheus.{{ .Values.domain }}
                      icon: fas fa-chart-bar
                    - title: Alertmanager
                      description: Alert routing and handling
                      url: https://alertmanager.{{ .Values.domain }}
                      icon: fas fa-bell
                - name: Repositories
                  icon: fas fa-code-branch
                  items:
                    - title: ISMS
                      description: Helm Charts Repo
                      url: https://github.com/loeken/helm-charts
                      icon: fab fa-github
                    - title: Enso Homelab
                      description: Infrastructure repository
                      url: https://github.com/loeken/enso-homelab
                      icon: fab fa-github
                - name: Uptime Kuma
                  icon: fas fa-lightbulb
                  items:
                    - title: Uptime Kuma
                      description: pings endpoints to check service availability
                      url: https://status.{{ .Values.domain }}
                      icon: fas fa-heartbeat

  destination:
    namespace: dashy
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{ end }}
