{{ if .Values.k10.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "20"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: k10
  namespace: argocd
spec:
  destination:
    namespace: kasten-io
    server: https://kubernetes.default.svc
  project: default
  source:
    chart: k10
    helm:
      values: |
        global:
          persistence:
            storageClass: {{ .Values.k10.storageClassName }}
        kanister:
          backupTimeout: 1440
        injectKanisterSidecar:
          enabled: {{ .Values.k10.sidecar.enabled }}
        auth:
          tokenAuth:
            enabled: true
        gateway:
          service:
            externalPort: 80
          resources:
            requests:
              memory: 100Mi
              cpu: 100m
            limits:
              memory: 1Gi

    repoURL: https://charts.kasten.io/
    targetRevision: 8.5.5
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true

{{ end }}