---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k3s-upgrade
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
spec:
  project: default
  source:
    repoURL: https://github.com/loeken/enso-homelab.git
    targetRevision: HEAD
    path: deploy/helm/upgrade_k3s
    helm:
      valueFiles:
        - values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
