{{ if .Values.nginxingress.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "2"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: nginx-ingress
  namespace: argocd
spec:
  destination:
    namespace: nginx-ingress
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: registry-1.docker.io/bitnamicharts
    chart: nginx-ingress-controller
    targetRevision: 12.0.4
    helm:
      values: |
        kind: DaemonSet
        daemonset:
          useHostPort: true
          hostPorts:
            http: 80
            https: 443

        service:
          externalTrafficPolicy: Local
          type: NodePort

        ingressClassResource:
          name: nginx
          enabled: true
          default: true

        controller:
          ingressClass: nginx

        defaultBackend:
          enabled: true
          containerPort: 8080  # <-- change from 80 to avoid conflict

          service:
            ports:
              http: 8080        # <-- also change this to match

          serverBlockConfig: |-
            location /healthz {
              return 200;
            }

            location / {
              default_type 'text/html; charset=utf-8';
              return 200 '
              <html>
                <head>
                  <meta charset="UTF-8">
                  <title>Welcome</title>
                  <style>
                    body { font-family: sans-serif; text-align: center; padding-top: 2em; }
                  </style>
                </head>
                <body>
                  <h1>🚀 Kubernoodles powered Homelab!</h1>
                  <p>This is the default landing page.</p>
                </body>
              </html>';
            }

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
{{ end }}