{{ if .Values.observability.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kube-prometheus-crds
  namespace: argocd
spec:
  destination:
    namespace: observability
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/prometheus-operator/prometheus-operator.git
    path: example/prometheus-operator-crd
    targetRevision: main
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
      - ServerSideApply=true
{{ end }}