{{ if .Values.observability.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "16"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: observability-robusta
  namespace: argocd
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: observability
  source:
    repoURL: https://robusta-charts.storage.googleapis.com
    chart: robusta
    targetRevision: 0.36.0
    helm:
      values: |
        clusterName: {{ .Values.clusterName }}

        globalConfig:
          signing_key: "{{`{{`}} env.SIGNING_KEY {{`}}`}}"
          account_id: "{{`{{`}} env.ACCOUNT_ID {{`}}`}}"

        sinksConfig:
          - robusta_sink:
              name: robusta_ui_sink
              token: "{{`{{`}} env.ROBUSTA_UI_TOKEN {{`}}`}}"
          - slack_sink:
              name: main_slack_sink
              slack_channel: observability
              api_key: "{{`{{`}} env.SLACK_API_KEY {{`}}`}}"
        enablePrometheusStack: false
        enablePlatformPlaybooks: true

        runner:
          sendAdditionalTelemetry: true
          additional_env_vars:
            - name: SIGNING_KEY
              valueFrom:
                secretKeyRef:
                  name: robusta
                  key: SIGNING_KEY
            - name: ACCOUNT_ID
              valueFrom:
                secretKeyRef:
                  name: robusta
                  key: ACCOUNT_ID
            - name: SLACK_API_KEY
              valueFrom:
                secretKeyRef:
                  name: robusta
                  key: SLACK_API_KEY
            - name: ROBUSTA_UI_TOKEN
              valueFrom:
                secretKeyRef:
                  name: robusta
                  key: ROBUSTA_UI_TOKEN

        enableHolmesGPT: false
        enabledManagedConfiguration: true

        holmes:
          additionalEnvVars:
            - name: ROBUSTA_AI
              value: "true"

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{ end }}