{{ if .Values.observability.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "15"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: observability-grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 10.5.15
    helm:
      values: |
        imageRenderer:
          enabled: true
        admin:
          existingSecret: grafana-admin-credentials
          userKey: admin-user
          passwordKey: admin-password

        persistence:
          enabled: true
          storageClassName: {{ .Values.observability.grafana.storageClassName }}
          accessModes:
            - ReadWriteOnce
          size: {{ .Values.observability.grafana.size }}
        grafana.ini:
          server:
            root_url: https://grafana.{{ .Values.domain }}
            domain: {{ .Values.domain }}
          database:
            wal: true
          users:
            auto_assign_org_role: Editor
        env:
          GF_AUTH_GENERIC_OAUTH_ENABLED: "true"
          GF_AUTH_GENERIC_OAUTH_NAME: "Authelia"
          GF_AUTH_GENERIC_OAUTH_CLIENT_ID: "grafana"
          GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://auth.{{ .Values.domain }}/api/oidc/authorization"
          GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "https://auth.{{ .Values.domain }}/api/oidc/token"
          GF_AUTH_GENERIC_OAUTH_API_URL: "https://auth.{{ .Values.domain }}/api/oidc/userinfo"
          GF_AUTH_GENERIC_OAUTH_SCOPES: "openid profile email groups"
          GF_AUTH_GENERIC_OAUTH_LOGIN_ATTRIBUTE_PATH: "preferred_username"
          GF_AUTH_GENERIC_OAUTH_NAME_ATTRIBUTE_PATH: "name"
          GF_AUTH_GENERIC_OAUTH_GROUPS_ATTRIBUTE_PATH: "groups"
          GF_AUTH_GENERIC_OAUTH_USE_PKCE: "true"
          GF_AUTH_GENERIC_OAUTH_TLS_SKIP_VERIFY_INSECURE: "true"
        envValueFrom:
          GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET:
            secretKeyRef:
              name: grafana-oauth-config
              key: GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET
        plugins:
          - ae3e-plotly-panel
          - grafana-clickhouse-datasource

        ingress:
          enabled: true
          ingressClassName: traefik
          annotations:
            cert-manager.io/cluster-issuer: "{{ .Values.clusterIssuer }}"
            external-dns.alpha.kubernetes.io/hostname: "grafana.{{ .Values.domain }}."
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
            external-dns.alpha.kubernetes.io/ttl: "120"
            {{- if .Values.observability.useAuthelia }}
            traefik.ingress.kubernetes.io/router.middlewares: default-authelia-forwardauth@kubernetescrd
            {{- end }}
          hosts:
            - grafana.{{ .Values.domain }}
          tls:
            - secretName: grafana-tls
              hosts:
                - grafana.{{ .Values.domain }}

        sidecar:
          dashboards:
            enabled: true
            label: grafana_dashboard
            labelValue: "1"
            folderAnnotation: grafana_folder
            provider:
              foldersFromFilesStructure: false
              allowUiUpdates: false
          datasources:
            enabled: true

        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Loki
                type: loki
                access: proxy
                url: http://observability-loki:3100
              - name: Prometheus
                type: prometheus
                access: proxy
                url: http://kube-prometheus-stack-prometheus:9090
                isDefault: true
        hostAliases:
          - ip: "10.1.0.101"
            hostnames:
              - "auth{{ .Values.domain }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{ end }}