{{ if .Values.observability.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "15"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: observability-grafana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://grafana.github.io/helm-charts
    chart: grafana
    targetRevision: 10.5.12
    helm:
      values: |
        imageRenderer:
          enabled: true
        admin:
          existingSecret: grafana-admin-credentials
          userKey: admin-user
          passwordKey: admin-password

        persistence:
          enabled: true
          storageClassName: {{ .Values.observability.grafana.storageClassName }}
          accessModes:
            - ReadWriteOnce
          size: {{ .Values.observability.grafana.size }}
        grafana.ini:
          server:
            root_url: https://grafana.{{ .Values.domain }}
            domain: aneralabs.lan
          users:
            auto_assign_org_role: Editor
        envFromSecret: grafana-oauth-config
        plugins:
          - ae3e-plotly-panel

        ingress:
          enabled: true
          ingressClassName: nginx
          annotations:
            cert-manager.io/cluster-issuer: "{{ .Values.clusterIssuer }}"
            external-dns.alpha.kubernetes.io/hostname: "grafana.{{ .Values.domain }}."
            external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
            external-dns.alpha.kubernetes.io/ttl: "120"
            {{- if .Values.observability.useAuthelia }}
            nginx.ingress.kubernetes.io/auth-url: "http://authelia.authelia.svc.cluster.local/api/authz/auth-request"
            nginx.ingress.kubernetes.io/auth-signin: "https://auth.{{ .Values.domain }}"
            {{- end }}
          hosts:
            - grafana.{{ .Values.domain }}
          tls:
            - secretName: grafana-tls
              hosts:
                - grafana.{{ .Values.domain }}

        sidecar:
          dashboards:
            enabled: false
          datasources:
            enabled: true

        datasources:
          datasources.yaml:
            apiVersion: 1
            datasources:
              - name: Loki
                type: loki
                access: proxy
                url: http://observability-loki:3100
              - name: Prometheus
                type: prometheus
                access: proxy
                url: http://kube-prometheus-stack-prometheus:9090
                isDefault: true
        hostAliases:
          - ip: "10.1.0.101"
            hostnames:
              - "auth{{ .Values.domain }}"
  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{ end }}