{{ if .Values.observability.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: observability-kube-prometheus-stack
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: kube-prometheus-stack
    targetRevision: 72.3.1
    helm:
      skipCrds: true
      values: |
        fullnameOverride: kube-prometheus-stack

        prometheus:
          prometheusSpec:
            serviceMonitorSelectorNilUsesHelmValues: false
            podMonitorSelectorNilUsesHelmValues: false
            ruleSelectorNilUsesHelmValues: false
            retention: 14d
            storageSpec:
              volumeClaimTemplate:
                spec:
                  storageClassName: {{ .Values.prometheus.storageClassName }}
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: {{ .Values.prometheus.size }}
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: "{{ .Values.clusterIssuer }}"
              external-dns.alpha.kubernetes.io/hostname: "prometheus.{{ .Values.domain }}."
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
              external-dns.alpha.kubernetes.io/ttl: "120"
            hosts:
              - prometheus.{{ .Values.domain }}
            tls:
              - secretName: prometheus-tls
                hosts:
                  - prometheus-{{ .Values.domain }}

        alertmanager:
          config:
            global:
              resolve_timeout: 5m
            receivers:
              - name: 'robusta'
                webhook_configs:
                  - url: 'http://observability-robusta-runner.observability.svc.cluster.local/api/alerts'
                    send_resolved: true
              - name: 'default-receiver'
            route:
              routes:
                - receiver: 'robusta'
                  group_by: [ '...' ]
                  group_wait: 1s
                  group_interval: 1s
                  matchers:
                    - severity =~ ".*"
                  repeat_interval: 4h
                  continue: true
              receiver: 'default-receiver'
          alertmanagerSpec:
            storage:
              volumeClaimTemplate:
                spec:
                  storageClassName: {{ .Values.alertmanager.storageClassName }}
                  accessModes: ["ReadWriteOnce"]
                  resources:
                    requests:
                      storage: {{ .Values.alertmanager.storageClassSize  }}
          ingress:
            enabled: true
            ingressClassName: nginx
            annotations:
              cert-manager.io/cluster-issuer: "{{ .Values.clusterIssuer }}"
              external-dns.alpha.kubernetes.io/hostname: "alertmanager.{{ .Values.domain }}."
              external-dns.alpha.kubernetes.io/cloudflare-proxied: "false"
              external-dns.alpha.kubernetes.io/ttl: "120"
            hosts:
              - alertmanager.{{ .Values.domain }}
            tls:
              - secretName: alertmanager-tls
                hosts:
                  - alertmanager-{{ .Values.domain }}

        grafana:
          enabled: false

        defaultRules:
          create: true

        kubeScheduler:
          enabled: true
        kubeControllerManager:
          enabled: true
        kubeProxy:
          enabled: false
        kubeEtcd:
          enabled: true
        nodeExporter:
          enabled: true
        kubeStateMetrics:
          enabled: true
        kubelet:
          enabled: true

  destination:
    server: https://kubernetes.default.svc
    namespace: observability

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
{{ end }}