# apiVersion: argoproj.io/v1alpha1
# kind: Application
# metadata:
#   name: rook-ceph-snapshot-controller
#   namespace: argocd
# spec:
#   project: default
#   source:
#     repoURL: https://github.com/kubernetes-csi/external-snapshotter.git
#     targetRevision: v8.2.0
#     path: deploy/kubernetes/snapshot-controller
#     kustomize:
#       enabled: false
#     directory:
#       recurse: true
#   destination:
#     server: https://kubernetes.default.svc
#     namespace: kube-system
#   syncPolicy:
#     automated:
#       selfHeal: true
#       prune: true
#     syncOptions:
#       - CreateNamespace=true