{{ if .Values.rookcephcluster.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  annotations:
    argocd.argoproj.io/sync-wave: "6"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  name: rook-ceph-cluster
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.rook.io/release
    chart: rook-ceph-cluster
    targetRevision: v1.17.2
    helm:
      values: |
        operatorNamespace: rook-ceph
        monitoring:
          enabled: true
          metricsDisabled: false
          createPrometheusRules: true
          rulesNamespaceOverride: rook-ceph
          prometheusRule:
            labels:
              release: prometheus
        csi:
          rbdPlugin:
            resources:
              requests:
                cpu: 100m
        cephClusterSpec:
          resources:
            prepareosd:
              requests:
                cpu: 50m
              limits:
                cpu: 200m
            mgr:
              requests:
                cpu: 100m
            mon:
              requests:
                cpu: 100m
            osd:
              requests:
                cpu: 100m
              limits:
                cpu: 300m
          dataDirHostPath: /var/lib/rook
          mon:
            count: 1
            allowMultiplePerNode: true
          mgr:
            count: 1
            allowMultiplePerNode: true
          dashboard:
            enabled: false
          crashCollector:
            disable: true
          logCollector:
            enabled: false
          storage:
            useAllNodes: true
            useAllDevices: true
            config:
              osdsPerDevice: "1"
              forceUseDisallowedDevice: "true"

        toolbox:
          enabled: true

        cephObjectStores: []
        cephBlockPools:
          - name: ceph-blockpool
            spec:
              failureDomain: host
              replicated:
                size: 1
            storageClass:
              enabled: true
              name: rook-ceph-block
              isDefault: false
              reclaimPolicy: Delete
              allowVolumeExpansion: true
              volumeBindingMode: "Immediate"
              # annotations:
              #   storageclass.kubernetes.io/is-default-class: "true"
              parameters:
                imageFormat: "2"
                imageFeatures: layering
                csi.storage.k8s.io/provisioner-secret-name: rook-csi-rbd-provisioner
                csi.storage.k8s.io/provisioner-secret-namespace: rook-ceph
                csi.storage.k8s.io/controller-expand-secret-name: rook-csi-rbd-provisioner
                csi.storage.k8s.io/controller-expand-secret-namespace: rook-ceph
                csi.storage.k8s.io/node-stage-secret-name: rook-csi-rbd-node
                csi.storage.k8s.io/node-stage-secret-namespace: rook-ceph
                csi.storage.k8s.io/fstype: ext4

        cephBlockPoolsVolumeSnapshotClass:
          enabled: true
          name: rook-ceph-block-snapshot
          isDefault: true
          deletionPolicy: Delete
          annotations:
            k10.kasten.io/is-snapshot-class: "true"
          parameters:
            clusterID: rook-ceph
            csi.storage.k8s.io/snapshotter-secret-name: rook-csi-rbd-provisioner
            csi.storage.k8s.io/snapshotter-secret-namespace: rook-ceph

  destination:
    server: https://kubernetes.default.svc
    namespace: rook-ceph
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
{{ end }}
