---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: system-upgrade-controller
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    managedNamespaceMetadata:
      labels:
        pod-security.kubernetes.io/enforce: privileged
  source:
    repoURL: https://github.com/rancher/system-upgrade-controller.git
    targetRevision: v0.18.0
    path: manifests
    kustomize:
      patches:
        - target:
            kind: ClusterRoleBinding
            name: system-upgrade
          patch: |-
            - op: add
              path: /subjects/1/namespace
              value: kube-system
        - target:
            kind: ClusterRoleBinding
            name: system-upgrade-drainer
          patch: |-
            - op: add
              path: /subjects/1/namespace
              value: kube-system
