---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k3s-system-upgrade-plans
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    repoURL: git@github.com:loeken/enso-homelab
    targetRevision: main
    path: deploy/helm/upgrade_k3s
  destination:
    server: https://kubernetes.default.svc
    namespace: system-upgrade
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
