apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
  name: authelia-cors
  namespace: default
spec:
  headers:
    accessControlAllowMethods:
      - PUT
      - GET
      - POST
      - OPTIONS
      - DELETE
      - PATCH
    accessControlAllowOriginList:
      - "https://heimdallr.{{ .Values.domain }}"
      - "http://localhost:8000"
    accessControlAllowHeaders:
      - authorization
      - content-type
      - accept
      - x-requested-with
    accessControlAllowCredentials: true
    accessControlMaxAge: 100
