---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_token: AgC3qinSvNu7+qBHhR+L4jXRGb9J8mtCXhfGOtyXQQEFtkM3v/3l+75eadnSMJFbnPOYSZ0/0zlS+mH4lLWGgil6wBPlS3ftd9CbEDgfHJ8il4vb2aLA/nCdnAznKChDFFT6ZRez7xDYxiqRGKbNpPVJ+bmb3Rk2acaDjRJBeyBnsoGRNTRSI4OpXL7X3vKOe7YEQnQr/TkMP2X1HTiVY/muu+UD/SfmQAGJ8oZO5XSSHYhqSbEZiJ9mtEA45tgv0fZ2cnb/mYjQiPZPpcj0kGIHmCRBYpNCKILhQDcxOfBNNhqhYmydc80XzhQYtjW/Lq/bGwhsm6s6jo8BEbklT1kGRWBFOIpmbDsp8iZZ8b4+uaaeD6K9VnfTynwTRS5uP1tCFDmIH+QRjlBswv5B6rmQ2LcJ0fqPklv3LH8f2MxQFhb7MqW3D5gUr+UsamUVz35dkAE/8UfbD1OYomyo+7/9XnZpz9zCeD485o2DwN0OTBv0uChR9McUWfjJzj82XDn7W8zdVNod26t85z8Ja3+GNsJrZxAMj1qmj/bBbvHaZEqBij5PJ62x9usS1PP7rkHvYZQSptYO/FZ/TPWvf99x0qgz0QtOFyUyeKeMBsBVEFBtUnpA7czNOYctGs1UkxyGlDXwJSUiKVH/swvlfyUVrfz8GB3gxFmI3K6PilSwYNAfLzHJ+sveSSTAEmVV7SVzgZ1JwUaUoOFm2ANMm/nLy2NMJEAcK3Ca2f8BCXpc8dDkbuNh9t9g
    email: AgA2u2LH3B8N/5ZJyceUwQcYyQUGtEe/etEOZAWJZWSAxtVW7k+OzSaO0q2M+xUSsP3U6YaD3K9zlfGyyX+kDXqMPHKRYkZwkBT8QwbIIQKa96n5+00fEtu+KtB2rAndcHyy4WKDlWu7/BlRclmK3Azp/dGbBvwxlMvcg775eGONNYqQ/CRX79jAHddSwqsfMKTeeLeLS03HZHJng4c6UsfTWji9nzTwHQiW9i4nj4JFZH4RGHe0Hw7GwLnr1botFLeOstVpZD53inV/VWJqCGVlXDjDFKxUOAFsy/EUhPRXmeUlIDv7XerJk4cZ0NIAA+HeXcNy6jUgajclEpfJBf506i3W7/pU8z9Tkjh7ir4Xm5dSMQxXY29cxd2g2ClNjUlW4ZDLTgbias1jidlKWC8LmtL4JeXWgNz+hA0Vn9D5OSd1Ve9oliudkM+Jsx4mkWscg7jXK+zEFYpPIElrXNZGLTY13B0fkv5tEzvZqWljpV6+78dFw9eIvEsAmusYbXMATeR7TZrxGCZ4ZUGlNyo7cMB6JXVn8zFQlcB6KfOROwT/CC3xC/YrvYPQklxI0AYY0/utK1yQ38q1ZtAt9+Krs2JF+aVmeP2GWMSSEFJSewUT5cXQa2Kl4DV/J/ABmXaNhK3dW7QqO5jqIbYXreGCAVZ0gjfaCcaCfR79VH1h7RpPHWfmTriEL0yGq/VdIGR6E0l+D44HyzcIa2cvW3NQJRvB
  template:
    metadata:
      creationTimestamp: null
      name: external-dns
      namespace: external-dns
    type: Opaque
