---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_token: AgAFV8R1a4mVkyNB1iSh7Hd/cd1v8f/Zo7ZyjJn+J1pK/OHFWb7R0VHRQbM4u1GUNo2D+LmzPJLAaClcpXtFRz08hOMeNwBStwYahqkFWk3sP4dxCpC6zQnwE6RZsFL++fBuXs24+PfC0WhUznXHm6XYrxfkRDa71sJ/7GskSLLwaNQ10F43YQ5INY9UPvk6v0q1MtfoHICoNHUXOJ/ona8dWOHn63KjG7MZfhPX6bMIXRHHI/PAuBDAtGPGOg2rhu6qzrvroAjgOd+X6tlBgTia9lC3s4StoBniAB7UVpWoR9aLDNPJjUhiPvwBpOkd8GPkC3eNC2lXG9okRwpvYxLcT748AxaAo/CMMKvM1Xa3QvICgNo5ZsL87gy2Y+J+rSQfWSklqINanMMbw8FwlinuyGnoIGE8HuNdoMCp7NfgIlJnlnuu12zntxDH9UQj7V35OVz6bbrzYf9bhajkcH34b8bPvPHv95C5GzOXoQrLcYKZ3FLGZ0XZEUAb603NtAmm4LS7Frax2oMx/0TXnEFnzzDt3urRKUR+zS//AmzdrYHl0SDODRqGFz4ASl5iI5IunLOva6oEgrsUFQhkPMSMl4SdgGyBFgaEAJ1i0DHn/Wl+6ow+dPbQlIorjpYhZjacE9go0yQ7+RBZfkxYIn51oQMFaXZ/0u/qITr4BrY+3okpJYxA6ZDCArDSogk8eCxmDzZjIyJgJukrzzPzTW8Drh5yrphDCjwiVGttyHo1lr7hv476hfY6
    email: AgC+FzfKMHGPTYUuo4vOlEA9HRr9hio2nguHanTYU+QhC9mGVXM/JlDCiPGDejggseQBEKF1ttkBh2SBkw4pvhejkKQursBIRjyvwINkmZq2bnyCAZk20L1IikO7FDnHCIsqpB8FFsuVKBhh0f9PqEi0umj66arsNgZcWqp65XIORhlmjBKBl712v26F2rFu+S6gR9QRFaiBRBhP981V/Qf7507dgACn4d2PDbOrBEpp5XNV0nMKeGRQM7JcGUJZdeABKLbg69BiIyYNgmGoqwO8+8VuJPdYUTsWMcYx9hMto4m6j4949YslmULj4f2VUlHcDPJm3IM1Pmj2Wz0Ex6EcyVbSTGNE4LeY0Nu4dncwBtMR+24JjRwjngZ/xMpAMMy8LyjMZBBAbGCRrbJcOPyB7YqF9XVsNf8LH1Cx9yyubueIepLfWHAZgPk4iPX1vxL+/KpqW/On+FpLdMVpqbhM0oXUqe0B/y7oy63E4gO1Bwd9CiD/ddQPHGgx/bPPkI06cFuJQyvkvDyTMh1v0VJtoYCfbsAFTf7G2um3qakUmkntpi7dGE9H6Jgbdysxe2Y1r1OqEZOTdWBk3oC6YAEAFJzeKjk9hPwt9Mh2gQ8ykVrdwRYj+W6P+oUxRON5XAa3R7zXslS7L8G27jD26NGVv7jA+PwGxnCNUXct73Z9jKNFMQbAqFtFifhtaRJwWKau+Y6TbqwSVbSBt6QZui1zkmiA
  template:
    metadata:
      creationTimestamp: null
      name: external-dns
      namespace: external-dns
    type: Opaque
