---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: external-dns
  namespace: external-dns
spec:
  encryptedData:
    cloudflare_api_token: AgAiASHgIYLYExNqTybLjb7J/C6eXMmAYuQ/x/E2sxyfBxcLnH3afJ2w/4fm8z9GUeDCUtL5cdI/8TsEABtNF/OoW4O5oqnDOnX6uRdDgvexN2MkdOEsuqhMMSgGjrhSfCJAIt2LxmjHlZZj5L4reb1RWpctBhfEk03FcNw15iPKglCc1Hu2QpFQWqGch4lCircMlGDEGmL3GzzhP4CRF2//x+DbJ65+HtYId4UzhUBQlqpIe+JcfRyjGM/S2ud6o0rFv7UIwCF8phRLjAnmvK2/4ZjDdmeu96UVYY+VRTk6tMa53kMB1X5Y+JEWL4mhi4XG76YLCBzWpOlbjNZCbiirnnJezzek2FPJVHB3svYLY2erjM5nnnqlUVxQavYr5j1j99iPjjnMh0CwsudTrZwdCtBfDHhYT2OdCEtAkIlkJZgZrcENBvnIZEU4ah5/Ud2GWJDR/n+RJz1k062GLn5Ce23/fTZJgJBQSrijUtEwe8b32lNLDMeAcR4lg/VDvnCgxLU1T2nxZNSR79OSLyHnOU6qfX/o9FmpcDzRHzOt/65oBaeRRiku9TcPGgstbXTl1Ra+OCxII4k0bB+kt+oTRRNI+E2yxsUMYAOQm6pn4RN+rBIaDH2JMZlOZ6YwFGlv+8DhYmieX1lpKR0fD5t0LGXxEP/kDxtwfv6PI+ehafYz6pJROGJvAwZ8Y7bxKRqZTB18uv1ikZH41WXMV5pkapbx1InrCqzKRsteWrnXhaSoN3UvVIVP
    email: AgDNKSppmSYu0p6TgdTsH9jeV/0OrWHgl+mdcOWEJUHTyRg6LdYWnFzVmU3vaItqFyiAATQ0uTBh5yhCv1I902Vdq2nlu/Mr3PsLRZ2V3pEkeNnpZR3Pkl0G0llAEJ2KcMeA0Y9JGX8sZcJ/a/Se6Vt5QuiWHbUVfV2TXPokQbEucuUW2mQnx+xey0RWKnEELumrtSz2kiSaS6PbCRL8TxhcViWVDXHeP/4oryNhejjuNTbR9fuvFhnD3KFtLzFXNDeChUtlzXeNlaGoRbqF/+wXHBeEQeVsB/WT3CJhrXhN0238wbHZn2Gcswzsw7DoyN3SEbyzY13tZgaWz9Ds5teO78OF9+Q8AZn3lbU6Tm/BhU6nCMqbNDGP9X9rxr6zhan+V1WyJNw84J9lhMzqwxa8cRCiBvT/UImecKzTojbNgpHnq+TDZMBXF6ZKz4GTTnJeeWzHmGZ+7nXeH7vzITHYHaEpSzZYhIPL2ZNqpkpgs76Oq2LfTsbnCTT0KwKNaMQUgs0J94tpu4Gumg9/apqAm49cbyRpZibZ7gxbkP2Iy99Jn7pDJPlR31FllaRK4Cv0tTkMVgXMA7wQjm5mfjiJLL72aLeKQ6X0hA9X41thi/Gpi40XcrbidAa9tC9YlL95x16A08bt7F96cvThUDJOIcrbQkw4+zt0eMsXIC9tubeuqTpGSYYoyDZbiaE+BwlwPusFjggUK0/n/aebK+0jHPsi
  template:
    metadata:
      creationTimestamp: null
      name: external-dns
      namespace: external-dns
    type: Opaque
