{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "mcp-credentials",
    "namespace": "llm"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "mcp-credentials",
        "namespace": "llm"
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "GITHUB_PERSONAL_ACCESS_TOKEN": "AgBhRNr8QoUnLaAEd5r7rUEZoYT5ZArwN+6RWWWQ9cMIEWWl/RLgZ3VncM3ark6e4CAHqLcxioFUGVO3l03O9d9E6pmR4PL0dk7IGNHMGlh5NjwX9NSqWK41CriC5DqS7PX/ErgVVfAIJgSD/2/QhosDnmklSjsyBTcUv29HlHNbSEiU+hUTmJUNTiVPO6a5aFGlnbVVpDIibo9Io+AsWer1h9lpe3hKF/DzelFA3IQKQCkKRmxpzctL5CeV4Wz0MQRisA5APhvpDPQZ6Q2H87WU4l/pd8DTxBJJyz1S0XWmSAIkkawdm0BljKg6HtCRZ7bscC9bRT6BPipL4+tn1KDa9RupVglbaDurw3huq9PjgDrlQZtWjyQ+ys4ekWsXAjmnWmFA/ZnPXuZa/vofCyNllyNAXS36xytaJNK7La3w5hTAGXm7za1FRhwA86OvqbX1xztrQ2PLFb0d4tswhbJknijBL8TjEKbcWb1h4QjZaKPEDxMtSLRdfP7wt2Yp7g2Th++2UYI4yQEskOb1MaGteItVKVNCPapPaxqApf4d5tebtDq+FgsQJFJZOQ1yOkDvccHcCVi2k4GYssDljYX1YIBqaBwQO0A1XxLa3M15WXkNgdQlYgZUpExnPTFBk29dqdG5htvm6mFU0nqahCQEYos1HFGA9Imm6zGy9a93Rg429NJRwfMVMl///KMLjD+wQR24eT4H3tyQh1TW5cKX3P1xjBSBVBFL7v5kkXvPJF7sWiJx4X07"
    }
  }
}
