{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "mcp-credentials",
    "namespace": "llm"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "mcp-credentials",
        "namespace": "llm"
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "BRAVE_API_KEY": "AgBnntIEkxao4PAUWRM6o2Cs4IVmj10McglU+bcx5MMK3vATIDZQEGK/HlWIDBmtWYCIa1IFS8DU0p/Sp/6TFmdTrHC3YO1fc+qH5oec7MlJCO/6iTY2m+fvDBzWXLkIheZiqeymd1qdxg3rP2+rKsKnDd/3L/KYGkkysN7YghLu6HLg2wJG0FFB86fXgbGl5H5gZ8NQTrPOtDa3GaAIs5jTmdlZrIyJy7rtDiYPpR/UD0SjOCz8yGFRiie/q0UWovr9m5OPTegP/oSJNG5ojhvqcyDVmHQhk9FeL8tbTzOQ1V0rahUvf7s333aXx/+qrkGLs94+sZ5WQP/C2lqkdhSNN82a+3Y1sfouJuVsOmgvsgdIXwwpncmqfX3UfSduizamYUjeF6N67TiueX82BScIFnLXDyv3/fURUVylhJiSUZ4FydbbaZtX4b6llZz4jHrPJTkiZfCfrOMPxSC/BTtHznkMNpaOBn7LJRa1Rg6hmPU9WllCiTUVEh0ZD8fMUXrkSonppXJUcxCes/snCQnVWHtocndZOrlB4N/uuObqSzO9NFct4pZI4M5eoZvi63Zc3MtsjsEjwN4fVd65tGU4MaQXQeXbWW3Y3/ArnFSXIom1Wz7aPc2d32HLjfgpkGFs0vljZ5fggWkRNC+DZmRUtGngYBDoNztA46gtw78uS9wKWTRK4awLeQG+CUP8wZJrFQDHl5ghR5Mpid43SSpSpGq98BeiEKiXwuQ=",
      "GITHUB_PERSONAL_ACCESS_TOKEN": "AgAWudqF7s6YTc6ra1u8ggZ3ZH10iQnpvRbwoRReCtyqopC4qrMg/XlyOf18YMITklf31yJzcLgcmqeTX+Hj1ycWQF2Cc9HBZytOX7DGuO+pAOB/i8WYL2f/xoRMQVwBSRri416QWsyKoBvfaR6iBq+T8jC/rPDj3MN3ojetQMk9FhhRHOumPYZXEQ+9wqu8vcKRWPZJGdZ6X5nFtXXoLfPZBfG1bFSNjWSTuB9hxnp2YWmdRvL+F3OFeK3rHnituT6xTkJjGLsQsxRlX5QJczUh0RoxbbEQ3bRzL4DO51KlqRXK1LDh9IlZwTPdTceh5fYnH6zT9ZbMm5BgQpeA3WnR7P2KoTVTnE34mr8rRHG5ESStB7PO/FiaVvyynyxwSlhQgBZ+dZXCRu6a5L9gBz33fjSVJ0mNEPNr/CM0pM8Tdzo1Z+MZnlQbnxis+utlzS+3wMQt9eIGYGl8Rff3Q+R5LFQ5n1UyKMr2CDp2g9WfThTJ3j912ph86ajdI9Apnhw2z0qQPeoR68z4FJq5dJkRrKt8dwWTjAv+KqkvJfnb/ir6PTgy+JxUIluRLysKwbOMskESulZY+J1dafH5VaNCKWd1upu/f0RacL+c1Ypto5mVDu5WhyBSlB5MSgiwD8Ali5DgLhQLYclyzymY0s+jtw/E4HHlsdRw0AI/DmFwRG63uFTp5PSVSBUq1jIckmfkvaZwkp6zqLHywjMEf337cUJREQA="
    }
  }
}
