---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: jellyfin-oidc-config
  namespace: media
spec:
  encryptedData:
    JELLYFIN_OIDC_CLIENT_SECRET: AgAD5IS/g5BclRA9gbHy2XtRN7Ykhx6KL0jlE8p2IbMbEhb0Ig9jpHZvojkp2ejaluoKeRHhVrSEcjqy1SYH24HVlobS+HWS92JUq245rv2T+VBiDkTEEEig7C30x4diHjxWpNjyeZVIspLNSv3PJHkpcx5kplRaTjSn0ba5B+hSl8fNtrrl+pxj3b7C4s4xMgjohDkFdZhyW9uzZ2VPNN1LDvb2vgjXtYvMItSFH7k8X/PqMpOV1C9g/sbA+O8tvUN2OA75U1zgsrp8LQiTQag2t7iZueXUxr9vMnCWDG+Zr6Fq6bzyH59LH49N6qz3La7iU+pqtMzLB1iBQ4XWgetn67c5GcK/TmB+v/1Ukdin8mOc5lcdhjFpxfLMVFGlD6dOyNx+H98OYL14qWziV7XhoQD5hZMM5X8xv0v5jK28pd1KZWwjgag1N8Cr1VL2DB6IjYmLKQ3WCIKW6lv6ZseXLe1UmXyTQjoNyc8eSPMZ6y7zt5+5SlKNmhCFKKjLBJfqvmSmgWeN42bGKhcpe7J8OwK6zlKo0/PIDqD7FhzmCe/yBAn6S4TY/LDATUStgM85g6QKKFK3qdHvYhFnNuzpNT2kuLU4UoEMhYGkzSa+Bf/fz+4RoeT+PA46hCZ8zLvM1+Z1eyftqsRw8Z7clQ3xcSnb9ixiimt2Dv5Ipm4nAACURH5DZbnrpmHwoQdBJe7UkWUXFfoTb13POGF1TNPY6Kw=
  template:
    metadata:
      creationTimestamp: null
      name: jellyfin-oidc-config
      namespace: media
    type: Opaque
