---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nzbget
  namespace: media
spec:
  encryptedData:
    password: AgBWyLt0Yy8dEvwjQr+t5vkpMAdwA9jGkoSuKiM9p3WSlTiNEYlq5WxKS6fV0Q2v5dZlbtc5O1IXbelbscFOtrmVdgeH2FSqexAcemoGDrbPL7DnTOxFitLnD3frJZJfiXuRyLaFDTUfr0EabQkI01+4PldEdEbWZTiAIWCQSq6cI3pbhOrpznkUQTk9Ize1BHTqo9Ud6G5lJDUbTtZVfH4kjFG+lBavKQ626A/3uL5N6X1VMxtm98H3EOJu3HQ0IiYEeHjLxSBBi3VAURocIW3+0mK/VEIlktnSJClXMJp7RJgOQIU8MYbt9fkEQ9Fa4Ut+i+Pa3HFfN7TioBMA33Reud9Wk9EXHzH/pB340ON5nZ3GPYMfSUHSg63freQ5vAGC7PrGXFYqeq0kbsYnWL8MTD0ZXluZcLkV2EfowjYCQ0cGDeZqiouwFwz00pJ+9oRkfjQf+uqJyGCXzgmEGzc2jZzWA/AgVvBiCtEzsIILII8HtrV04PjKaRvl7GYBXRkMmVmH9LC4GYxwKsJpYFnsLxfap5g3XO2HZKPMV0I4bUj66fSpXy9Unm3TagOn00KOwJqyNJl2fZkGjtg8vKvJtxmvvHjrAknnXv1laJbHe/czgSL/5ygK4HYRT+hcU3bd6Ee7qR8Xa1bMrfviPm2Lpl9O6WRzwV3fGXOWUeZFX1leC4UMgH9ySYkbCo681qNVTLn67hbXwiBVVwr/3w==
    username: AgBWPRIg08d1I1ru4cWkn8XHl04zFdrAec6qAdA64vSHiXSn1hXz7NGOHYf3MuCbplZrOKfzvixrO3sEkhJzu9/L+63+xPYOXvTblo4d9CPsWz/wVrKrr6gS+Dps71wfLTm4FKjABKDepBkmBah1PmRV33iKfh0PRgS9pDnLjIbP8VyBLTnwHYHWPTSXSsz1zjzOFf0FOrK8BC3Ezs/kHFq0JkSM+0xqXkRPOXMbXgnjxm4S0miULBG7mjuO3IX3RG/6NEDfTEnyXtnDUmjPJJy3Gct0tXiLqIaktTMw6102SpW2kShYxS+2YYu1JuuB6ULiOZdfONbtzOfW4M8oq4MacrWn5G7e1PsNENCP8qHYMH5DPEOvRFCcusPWG4pfQ5D684xmQaXdNX/Jqyk/hs4sqW1ROr6Ngq09/ex0iu/ux6E4EseWI7BKXHFgt8rPDKUAR9m1TpjOgV9CmwghT3NmH0FavQP2gcqv8dZzlDyY8lJr/LkoVS7ho/1p2di2pc5/4fE/5+RQiDmWPqWnh8qzljRqe9HMn7VNTAVjQBaVAt+VycQkayLaiAew8LBtE10Sy6a4xZ7FIkf8f40SK9u2bSyCiEl/L7Hv4hg6WP/c+6cK75Uo2hSNoq2ygFOZeH1O4Gg4PpQRvccoSPWH0kObhzFutM+vgaDUd0nXI0vaVRGeZHxdu9UdthyHdpawEWvLnk3CIqg=
  template:
    metadata:
      creationTimestamp: null
      name: nzbget
      namespace: media
