---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nzbget
  namespace: media
spec:
  encryptedData:
    password: AgBPybTRbarmFx+mgIW0SQaKL7S7inS+z70yjm+aeZyhuyzD9vs+/JjJgWxNTWwRzqOh3AMc/4x9GvylSbiGvzWEnvWKMX/nhFQvWAcmLb92cqla1TIR5lzfeQp17UMh7OtTaYD0j0BE19+fFGyJzPCZKnf7RX21gDM1tN/306Z44xnYqUN9uaX2JdL4yy1rRfZBG/hVDPTCxg5IdPfdNMjNarkCqrEwZwIJ7YwnCvc5T9l67sFo2QnhIQ3Lb6D5z/zlc+E0S19JKn1GBDS75SA4aY7lu+wO5gpH3C6hhqOmvKj2HPDEOEIUu6h1Ov4IRtQtikgUqz21TannRFKpCDaWmRi8cF2LDYRe1djQB1HCs8T+0CCmINnw5uFCrJIwzVd3VI+LU6BzZ2QomEqmXTjAdqsi0CM4haWZPOW4FVU9l31rPDkFZwEYRaIef7K1VC1rEpD1/ljri7KwO59hmn4YzKiuvcONVPki8qymILEk5L1+r2N80RaS10EAcbhpnGDVwagJJz2vOFTN98uU5SVaamsxbZ00VVXrSC0ouwfQobHeWLi4vzpa/s+YIHXtQtShVLYL7okYNhLc4aka3n7Uwd9hvHR8NtjknHi03RTliycMomkCyDx4xTwtvMA+LG0gSOpEmq+au7v7a1h9m5La6fDpAao1qy+Iqq483RyXdGbC/dJaeqdx8MY7F8sUyX6k8l0L8Sp3xHFdxWNOvw==
    username: AgAsXFbZwruuAKV96ao0IQ4Tsle8FuqS8ch5apZHAAv0tiw76y/+95hf3qZb8+dmJ1PuP8untVATTA2K+1luyt5klUILSO0Ii4Iwy0iHLaUpT4zz29zqX+VKb13Yal3S25fO9Bw9s6jFfh6GiLt1l+Uxrvef8D5Y+/Jof8XUZz6RhIYxVES6wlOCBkBTijbXKqmAmtzGIlO/BIEtCvt1zanuDUa4YZhjyMrvjHpA9jLyS7aLXkFr3tizUR/ri2+eICOJCuXNtscu2Dr5C4u0VbiZ9m+lYfWJA5L+E4StsmmMi/QdV39Wqc26K9lODcmRtX5l4HjbovMeNqNktbn8nDnxc9BZ0ZsPCQ5W+e66zvdWLHc9NFgFJiONJP8q97mQuQFsoyCGdH5166Dgo3o5yUgUG+LmQaYdhoXM1xjf4UczKY5Wi2TDQTHJ387rBD6ZssMX9GCyZA76v0eNbW4GmabgOdgoivfa2WEmiUyq9pusuLxgNys8osXI/NdWDkw3tvu0Ph+tVSz0EsSGZY/cawiJtBBqbbpcJnkTOLfOosRyBobdgLJIX8cABB6GZMu4OKsxoxfDoUOmp9vRyb3doZ14x6peL9ukGv//7jCwF0Sk1ASWEm4CD56q9Syy3+HXwddM/pivymtOCreFpUmNNmZxj3eSmOV+tfjmGwY0vRNnoqWG1SEDfItGsFUyi2zPLhfl6TontxE=
  template:
    metadata:
      creationTimestamp: null
      name: nzbget
      namespace: media
