---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: nzbget
  namespace: media
spec:
  encryptedData:
    password: AgChkccukYYlZrurSS/0fY9xUsdE4B0d3xmKLEmuZEsZxIHnNOxRnrAEDMupFMpxIvpcSilOuX+TzswuhrDwDOhTVTefTMQ1GrnIuhQZKy3LSIU7z5y++m55ye8h0mRTdkgn3IwRSDoEComHrvYCUgH+OyqSzMIK+JeDqC1o7m4stxerg45RNwHjwcLYtGK6Uyvh9k9ixvd72gfMLEqYuVNTtALYVAAxMa78fAegJAG/xDHKd7vSGCDg7HauCcr0sskCwaX0RQRchWVGy3G++2qDMVe+s8u2Ws0L8l4/Jb0saAE5TU3Jz7kSCWjsGu44lW+3GoZzvhz6CtE5AI7+7E2DNfIds8cDzVmPgsmHPGf51IHP3/GyM/0OSC4/d/rgqZwKaEjwPpnuXj7j9lwfR6+YWwpeNjBoYPqJeQK2bZI0G5Ko/uLEhr3+6ecM1wn/Sr8TdZDDvkMxAd88CGueeQ0Tj5TFzks7sijHi3lR5IFYtwbWvLtm5o9rYpwwk/I7LbktbnOy3RYDCdszfbP6diRwVPbqhAZbhH21zfpqW3aPN73xMF7NlOKtsGIpssHmg/Cr3M8LfU+rSWa3jEcgyW0Z/0a2MDs24AggGRHbL1AV5zxggcacpu7hMjbckIgW/9Zv4IttlhZ3hbb5JwGVvWcllxL34BRm99LalBkjkaQuToBNEhiOLKooJsODUWgue2T3Ub7c+7cTijCGO2FhSg==
    username: AgC+7GEalZJT26YI424q+Zy5W0r5pC0JlqIrnJdfRbFqa21oXbegILhL1rLiuGYiMY5WhbupQXwKRoWqhC9yZ73ySqHNknYIjqgMxhxJGgwPgjuk8tSYgsTx696As5nQ2cM7a7SADudQ+9bRLvwxRH0i8D5uJKJbAjrNYsz2KIH1oF1xUthhyKpLEsTJQ3jEABbpoxHVlLP5GzRzZRT9O+JsYWliO6iKTjTMEh+IydkbvfX98uVnogAd0DtjQo5li6URXHGV+oX9qn0BIR78mFSivA5/OCuV2HQFOeliQGqYvcXPp72x4r9FGubQzqk2PhcKBYOZx2ZafeJZo+a3uKetVcZEQdAQxlEUFYag0rtu6mH+UxVmM1rGJQLhg0cYsIuSyM3ygSu6+Hbn60EqbZcS82lph3lbZYVW3dT+LGLAbymx+op/wuibd/Yk2pmkWo4LKXK4oeXJWt1lVdBCXPZMRxATlE4Ry75IcSLuKkEdNGu5gP1ysBcSfD6B7jMQk40Wc4LAkiJfATXvvGTzPhV8x4GAeiepHC83vJIn+hJsLh10WIPeyrNQ4AmV/Jni5QjPPmGpEDlaePnceJBDiJjOkKog1gHJbJUxE8vRw2Y0ty+iwndUawHzvCUN0MmcWHZpUYmRzC7gwwODp8mQxrx9+BnTUacMLVGmPQlnFEWmSg0MpCtfCIlL39iltDpKqWG40lVzRuk=
  template:
    metadata:
      creationTimestamp: null
      name: nzbget
      namespace: media
