---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-pagerduty
  namespace: observability
spec:
  encryptedData:
    service_key: AgBMd5wUrya8k2PXLeeWcN9nWD1ijkuAOckVN5rLqGAJIXdw3T95sdzDPDVa2Ml9/0U58B3kArncIeToT6bg//OfZiXLf3XhGcL7T1NkIkT0uzFlpE3YR4AwAOB02R2+7FG6GryfnO0r2PG7StcVEXLVD7+s6exXUuSmkWsLaARsnIPi7/3CXhd/GBuSnmUtevw+5Lmo8p595WYSj6sTQzM/NZh/RRz5nfh8R9yEt57ZQbPvG5RWVRi6baoyxYdlaxIam3JCkAT5Im45wPN7dQaCOhjptnK0rchMURBLG41avorIvOE1TPcjyBhR8o43bcsbQzcE0hCt6hBnjkSe65ny7AUiWJTk2m/fxw55oY21an7HAjLsA8h0cacxOxc+zSFtbnIW2DyI/NrrklCWN+q5yP1aYRMCG8n8TUKfB0o93WlDj/ZoOVxQIrMZDLZvLnC0fXjPrYqZamcyKaBZYuz+TojfI0057O7Zfzy9qCIDj588m825NxgqF4acDbuXP7qaf9vlpAsycSQaWoosulOTDkLbuMRKibjMCmM1ReWZ1pSKGpux8tVrPEJwdyKmOE6+Tug2STyP/TlF0XNGPOsVtXiVk1AKAEmCI3BNtb+mRDqkRuoK3YMdNX5WzdimIvK/xZDklKh7S8qF/amX7Ug0Oc7ImEbkU6hLyfZ/nQFEbqQG+lksrPVoZEobhpxalP2vAFuAqn0bASCeAMmJFlTLQRl1Z2stwqks6Td8RNOgwg==
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-pagerduty
      namespace: observability
