---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-pagerduty
  namespace: observability
spec:
  encryptedData:
    service_key: AgCmiLMXWNWZ0/7qMQRqUqVRDmCMDJ/wLnYRmY1JG/BcQCn6qHL/FgBmvAY/Z+7pKIJd2r2Ur4xUBl+4hYo94B4zhS+vVkPSKk9KqkbmkKCM/sGRMwDX7ZQk2WAPuXrQKZ8t3NLTKCASCzY0XkMx6T8wLZGL3EANVrapFpancl0G6ovWli7LoWRm3T1eYMGieqRZXsjfdLzAs81MWepS2M8IvfgXYumBbwAvs/0QVrucw9yodjcYPqLGoyIcOoIImAb6MSMXLNomh/fMoeAIXBte4uqpRtBdY95YG2/34AAsts/ndhJPDW20tulWksrLRDZMcZos48d6Ciuigda7xn39Y2gjpkbzQhkjL74oUTZvhk5GuiIvGfnqQKSB5PnO/bdOO1TtK9s7SX7t5IjJe5OiZlPX6Wc5IdLXoUq5ef49fMv/Kgvms6O8SKYSKi5pHqQrE5fTVdwCr43jiPqbQm9Ih9S6+X/sAdHlNFcU+I9wpsKtuSRBvucyMRIsn1wED3QXO7brCq35d4Z6lt7lqy6Ho0/kYHp3CQQjE3pXZr3SNFOkU3G1shpPhbLS2ImxH2pGgM/2k2CwKUn0+K2fJhL2yREFCcWggupdvi5gQw51ixwSKPDfzAVtWlno/U3dAfPc4naNC/hFPzW2L5V3OfWqZb3URrK5X2cijddqI62xwAtFyxVdgolG16pi1DdPPdMoWqbuNJyMNHCCOh0MbpOBOgKHh0SPRM1K10UfiPE7wA==
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-pagerduty
      namespace: observability
