---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: observability
spec:
  encryptedData:
    admin-password: AgCvTiU8qucg+orDCRdoSAI0kcmXkQOGNptdXj0Osl7FxW/VJVkRdfA02QILjt4jpvsYDNkaaKi2NOeReaPD/RX+LCspsg8YaQn4fDchJ9ahf0dWHnHhZJne+50/XxTwhAyYOziE2Yy2+QlhqhP7OImkhmTt/tISJWyXr7w4jqFoRfeexJ3sGd0rL/hGMb6efF6HRXauum3Oquoz8V3r1QTWEepAWYAlUmYejRrumGuLL/by+imuWslhdBUc4s7cDTd+de5cb8kBJsR0iKaJKMhFLUl0nyeE9nKzc2vUzvx7O4ob7vCohaEXBs62VhBdrNfaMKgBXi6WmVhxqU4DV1ss51rXmOdQYQOUAAo4cJk3s0gKLc9M5fbjxsQrhek3vUHTyG3l9XcKBfMPHKLSpDdbYngMOPxikUgeheWBV0ZxYwfwDgjPA2zaI42ij+j2neWQl9fYb7OUcUj6LvE1M2Nkh5yVEFeetUAFhuE0NELdD1LHf1b+EVF7+a+E7Zs4FsqiPDfZrZ6t2Kpi2vctgX20hwaUxXuSc+eztrGvszH5ojukgELeDkTLd2Jzh3OEd5smDNkmQKDSKBW2nIAs1dKODXufWtp25nAkoh79FmP8AbVllstx6KVN0pWe+//ZDTmeJQRbm1cdHdm51hwQ0LkH9M4jyDTk6R+JcXxaa7Gxa0wI26qAbIYZgrC+PQZiOGQmrp3m1nFsfK0u
    admin-user: AgAwE/z8xajUClo5Nk+DmWlwl/qkobvRvDsHOhB1AX2bgB7n96mqhKUeApaGS7IPW1ugdtc8AazEcWJCO8dFQ7l/P2LB7SvXwqx/Whj+l5TaNvb8Z14j4UTq6be/P3bBZqgBKaHwgQqNYx5sewUe+NWwJU4BOCdimjbJQnYu7ylgOS+7rhGWzsNZZzton74jG/wpQRH0C1dpa9tXkU3xDnEBJB6nFp2IGPJp3+HBqikE2VuYuutlbHXf0bLLpv+yxZ9QuCDLN8hCNZvSqs4Hb3CdGbRj7DwXhPRYFOmajLZltgfsB3B0Sm+XSrJylug984UTKCf3GJsAMjN5pCoXjZSzzSWh1MIT7XxRdtnMuMpAyUqUzp8/itZ7aqJ4MJ1mIc1lS8oQXchXcCuPq/xdBS/cJeIW02uFi5lETL5sjAkTf09GrabCAYfF1II0OI7pS4ME40E7c0vM/49JnOCEJfN/G1xGC4y7w1Wz+jXQiDRJBT+XVr6VwrkBwbrheD/UCRJeaebkI+3Khaj5KWNr5+/TGQIw84eMN+WCtnYsfTxvqtw6WqkdZmx1Ql1JiYgKD7KCFWBxaNlPUF9Bnwk3NehKS4tYCjmhkwRYDCn+n5vLbMFsiGbQv0Nvd5uvQ74yHf4rXPGEG0zE8MCsvh1d8rcYmDQFFmQyBChHgJLxiXA3NWfK4R9IrqV5TvgxZ+5/toPhGpG+bA==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: observability
    type: Opaque
