---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: observability
spec:
  encryptedData:
    admin-password: AgACztVu1ZGQjAvbGFiHsWwJp0J0fWFg9QtuLlTYOvcI2MfM2wLbV9qt0Q8Z4od9rkhIihvC6Ix73V8dWurW9xRrt3NLbJZQF9CQ2Oi8bRUvIwxqAR51CGCx9p4FouztPCRXiOkeXksAm87Pn/lmr9TJC0iI/WVbzt/DnWV6ef5jKGtr5zVMPxMsl8KEnhOsx999l/TZ8RDqFAZL0E6WD+j0H5dHUAfbMvEvaOwOhKBiyvE6rfQr1S8GDKQZiG6ASbw26opSM1m2tojav+Jf941qu+fydVCKVOCUMmqVZvlwgX/iBiQ+rVa/9fkET1YKOjBZQmiJqDCZmZd3cNz1QU6I1PMGaSJwQIu3iB8elrkn3yRVz7i2lPFBTnwDa2sSY5S4FxKP9GFF2NtOdyr9QKNxDvbuIorbV8P1NZUrO+3lAGCRwXZyS/78FIeTbj46VAgec0r0c+gpgRqJxCZkq2YVDM8Jc/x1B8k0UyfEx5IVlkSLYGcJp1euyygerhCPC0bKKHfl7Wqdvf4p19Aa1Oc0gLOFU00jgM0IW0tg6EcSHGwuqYkO5kgdR600U+D4eCQa6XpQ7MFapZ9Hxvf0u+PdqHyiJl874sjfrP7cVQUzyk2GipbvJn0NlGK89sIUIqXrFQCmCUDVLli4gZWIrZOPkrNMRbIsw/ZPPDQcMBS51ZHYO9aULO+YG4O708yA4dXP5hQ5z/sneM+8
    admin-user: AgB7lmZXaFY1zPclbVar5OAM0QGCi4TbwspeJhLUKTKISBKQ50Mo4U1N/W/t1np3GNePUCIkniMiQrZ2iQUXEnJJXoN88kkjI41mqZ6dUGAd+sXRL3HfwkW4GZoDuAnYaZFaYrHGWDyd5NlCZfnviqR+/ETSlb4Z/dJXlX76UoelVAydufCfn/Umu6zA3LQWrBK6+nKT7LklkCkiN5VEwBTNc5oPKLIu2fm8INgRRnIggYlmoC4nUXbZHxYceyegNhSXPaekqbqPSnqeyyJD+exMCw0mz/5bAjMbnF3KLoz36bsQcCJYAnqupHQlhC4THaVMtM1yWDPMlEGcsPHA0S7BTA4OswZTUfRf3NtD5c8eWyhf5fvgvdcNKYhs0J4+B6iWl77YqFvY0bg3h6FLAbld5vY/e6K2oRMjiRT8JWHeWumErAhywVCzlpWG4ZEm30X8nFlYWCskoiE3FNSni5vjsXcI5bBIxajGwVXFOdomUnRRgSurXoAR6fNpiOE450EpRTwKEk+7e+P+kBCBp6TDvT7OXoTsOWS/plJ8CC8wDAasXambbet5UxY+29uHg/+QvGxLbo8CNg0g+i0LabJOrIgL6NyOy92o0obIYImeQXOgvrn4fAf+JNiEngMPMLfGk5GS9otaJccKH+Xn9M7YYSBmvuhxfDwxPOGs0SWSWJiptYBFbCS+rYmwLz6NgedPCGaG+w==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: observability
    type: Opaque
