---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: grafana-admin-credentials
  namespace: observability
spec:
  encryptedData:
    admin-password: AgBLs5Imp53l7HKSgMNC3PVS62+9dKjozSZlxZZe2Jppf9fr2i6GAuZ9oTEjTSTBnbD68oc8kS4E7ZPt2QT9YE86gEnUn/h86vdp0lNHv5cl1KB7t1ylZ6W3cT2Wqn5dF5ahvdh5sn8aJyG1kXm7D9/lEHZBnD9/pHUcsciFa0sPe853NcSo6YjiUJsUKZn5t+Mt1nujsFi8ZAz/xRR/ebMRBKkU51IfhwFDzD4xdkp+KjQA86ZQsGTfD+8G6iW6vDtutrMF+ejAgorVe1XVXpQdhLFzevN/T3jmz5KnmpWJTBKs44dcuRvhxfH5d777ocRm4ljs/6fCaGbETx1dTR+EtdRzyE7zsxENFFrFXPrrBVRwqE7hzEpmyvd3T0YjFgmKyLefNEtQljaDRHXWd97Q/GP7F+3HIGXZVC6R38AcQ1Fv8qG/sXvzD+D2M2KNJgy/i0BYRss3wiPPATi2gilmUxf8XE9RvhTbwOasArX7VQnIRIyTj70cCGdP7jXYbPYgQEMZlFGiKheg6hwb3YDCxLB/QuFO0kzaek8DbLD4FPIxEA1tuvudgQM4VVhxNMq+2sGJ/kZBrE2u/0gzfNajdITMfcVVf3K62bCfZzsQhUaXTxAcXfhnNOH9D6FfpUfHo/ABiGsQhfIoia3JrUHwyeXIpDSomYpdFqrS5Fsm/kFYDnzMo/rPsRVVwkupXMLrwy2Soria2w5d
    admin-user: AgBXajyk3G+OMVKPsG3Jp9Jepok1XEHhp0Hs5FajJLNzZ/iBYXSJMmbOIktFe2+VvvhOCG6Oomg2Z8IEzc8BGkk7pK7HP2C8DkkSVsBqjm7+4gUtRyLAb3qwRj1To1zTqn7CUUpVeFsf4FxglNwwYMbsjOkod9b8sDg4D4YcYHgJkCa9uqBmGTd8dh6SS0St7nFHOOUbgL8Dqnd7sicuVseXUV0MT/FlEIv+o48f7SFsPudQFxYJhupYC03EjCOrAdsTMc8WpP0M81ALL+gIhOGT6j4aRB7J71LyoH4aybZ77xDslukJNuhcaexW6JAPRvbG2ocZp1WsH9x/DAwA6kDXuMtgnzWB0zDmY7AP58seX4yCxBLk1/A3jg7Wpvv9d2Qts/JGlMIztozZ5kQBntzrq7yF6eihNY3BK6zlSg9ZORDEcdaUZ9YFiMr0rdqD/MgInIozm5iHbUr7ZeSlWfCp8zC0kz6hVxRLYhMp25Ux45FCui7jp5Tn2bAsorYlxoeH5I2DZj8Gd0en83HCfMXpj4ZY77nrhdoRolqYDPKaG5LfXwuPjfhz2oOQF/AwUTUFdOq3NhoooSKV/LsJRNn/qpY9Npef/zhXe+Bhtk8UkEcIKFKrj9MYtsmpoRjfYTtWbVDEzYpyMew5yu8IqTP86tiCfzkwYV5dqZwzlqNLglLES4ZU5UWSVQIX9oFGsYWwYn4isw==
  template:
    metadata:
      creationTimestamp: null
      name: grafana-admin-credentials
      namespace: observability
    type: Opaque
