---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: alertmanager-pagerduty
  namespace: observability
spec:
  encryptedData:
    service_key: AgBEbyRyE0O8jI8v/gjMuaYf9Jm1XIFIQKx0Pr838NVwfrrmgOSPGgEkAhkBr7ApPVfyfE6vshuvcmXJppKMOMlfWU5B7xW5zJ/k2lLpvbrJm1bfGPkl67QMIbxg4WLm1YAw1K9adLZhb4198GvIhYI3/rDiNeAgMYA0jDkLszbhVQIy2VZn+kdbk15yPn+AiDreB66HWOhqkMKFpkVjJZ0b44XWg4gAf7PSuQfYs8bztl6IFzed55EvrcTB1jYWqNjMphlN7Mvr//MaSRO/G/XZ61ctFj84dR03TjvcvOOSznYlQLpq+xrjOa71dpRh2D0NXDIXLk6dLXJUbyLUbp4BiZ4nnmc1jExfn60hHTHDBJIyUSwK6+KVvZVe4O+tF6gauVixjG+K+cMBqcOCI/3rzq8wdmSZv/MJ5ewOtQj9zHXtPrP8IxWbUVF85TZ12P+NM39FMwRnlV77YuGHGAq77pmL+XTGQ5Mc8oh1tDea/AXsFEaj72knc1v4VW2WLBuHQUZWoZW2U3a7zaC3iKnmB+zKIDOsc2fQ4DjgrRqIhIQatAQTbsOrdlTCN2dxOaT12JUszdk6W6xQ7PdI+KdzkGEsDd2BhgwO8vT+OTsrD+64o679pu1WkXAaMuLeBu/glqrDhXo579UKUGH6FrDeVVQXOPS2u67qcLHVLAqVdSRh6i+JTKjZFLEntW5AFrkvvnS+Tz2TZ9uB4k8T/wpU2yzIhIRl5JEr8mVo+K6mLg==
  template:
    metadata:
      creationTimestamp: null
      name: alertmanager-pagerduty
      namespace: observability
