{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "ghcr-credentials",
    "namespace": "the-machine"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "ghcr-credentials",
        "namespace": "the-machine"
      },
      "type": "kubernetes.io/dockerconfigjson"
    },
    "encryptedData": {
      ".dockerconfigjson": "AgBHiExGt/4/lrnaMFm8BqLzkutaDCT6zCLYdD9I3wMYJd8upVpvuNHj8tgQiF2bq1LfmCuUsqglgkAiyzD3uxOjVAUHmv6/4Tg1lojSAhrBWZmCnUCzQibgYWZL1/Jtm6tywi4D92SPRYJsIpXtHBt86GLF4S1TJMY465K9DSIHCEeqYFy/CFK5lxQUN4FRi6J9iPK0hsqfyMpOYk82lPmEBoHIkIxqwMDAv0CKvaFMypJIWcBtSgtaKEcU1PNL+UFURNvHiBGeFPbx6dnAgbYC3lURDdL7FhZN2WJP9054t6+PDoD5ZxIBvR4LrRzNfLuN2WRVe6vInaYnQWtF2SJQGvQPy8zQQhgAeLcUZlQT+1oNB/krV8QVrElp86Teim9NhiEuIW1W7Cuvbzfd8IIAIrf3jd80LT6on2v7OQicrT3TkE98BeDzDQ8lzMcRgChHigG1iE8XtctTD78V+Zo+7U3JZm1+XN9UPeaN1SnYc18vsFF57tqPrRBEBilqYDF3V6PHVXJouADf/TORUTxPr1DF24pxh6TpTtn47hn6jhcVAJJr+x7duuI8CIzEW2qT0DWFKFx8rTMibhenmfq9uqdyRjIAL4Mxd5yhGb+HKs02ZcT5obCeIRV/28NMx2U9noYKK8GggXLrzw2EviLg0cINJsiJmatNrMFuDlerOzOlwakX738xeWCCPS0OgSSSh+qmg2V/Gj/g3O5htfIxEXbLCSE409SbXAgxKLQnSggQFXpJQCv+9B5r8eo58qmwYwEe9eQek5nMi6hZWaG3Nhq4/rlIWz7PQS7Z22PNMoaDclg8FROyGI/WgASCN7vQ"
    }
  }
}
