{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "ghcr-credentials",
    "namespace": "the-machine"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "ghcr-credentials",
        "namespace": "the-machine"
      },
      "type": "kubernetes.io/dockerconfigjson"
    },
    "encryptedData": {
      ".dockerconfigjson": "AgDAyk1V6N5JzztOcOBkeFYskl0J9+RF4XvQDHel+cbDfRzo88qCDqPriNzdroHt3CgpNvTfCmGzvi2iMq8qJHYBKNsSy1rSBxDrKHnUrWjgg6Pt9YSw5obFDuIwQfQLHl8vHSB9Uqdf8RKTAW/nhV7QREHpvWtaFDilYmY0y2kf8DQELiuLUf+HfLQfr1A6D+fGn0THSiY4zKMXTY+fvHjkbHlfvOXUPmZc/1pJF9tcgsm5h5Ou0imo5reOSEzf7Eqy92haq9ZVH651naaAiWAZXmH04U7AlBy3ZC+4VmRTPryd+dn0V32U6zhKs9Fb/sFkg4xqL0k4AbsbUvrvvXemrOI+xJ5aPK1+7l/8q09959kLSh5OPItU+s/coZMHTlzH2+PQ1eJ3JMw+T/PbJx/A7YxCy3HR4/Ums5cU20YQCcXbOuEd4Yxc4iTHnjfIySQetLujgxtTrXerlDHDkvMJ3pF3JTjYEPuKfBeCrlGIKOYt2iVe/vKUu7JId2CMmHy9OIuJeFFLbeSDygC4/kwgk2vHPWOIL6peQ8KHsN/ooCXPnQ6WGTfGoK2Ohzo3E4ANRjhwA7pAf6kcYXO94annr4yhuFTZBTjqLd4bCAy+h0/H41n9/MhjxpqVB4z89VSQD11k3+Ry163BEq0k2bQJAfYS4uddqIo4CIC5T4r/Jxse7YgXvhygIRZKr/aQrdxVU/JPxhyLlAtXFe4i0G9MU6e463YIzwRy1Q5jRHY7IBqTI4DPxmbbHeIcj8urlaCpJabXMJkTTnLzmEYN35pKCYax5kwzJAHu5tHyNdakji6f2cu/6WY+DrDMTEZgNsId"
    }
  }
}
