{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "ghcr-credentials",
    "namespace": "the-machine"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "ghcr-credentials",
        "namespace": "the-machine"
      },
      "type": "kubernetes.io/dockerconfigjson"
    },
    "encryptedData": {
      ".dockerconfigjson": "AgC7R78ho3rTZChQ1b+ADpuZDG5qSDGe/1aH8AT/TlB3DRZKPQ7etYTROdB6TH25hN+7BhlXWz/MbvGabwPWJT5PMUMm8HpjCBF9/X4fetGVVBlOeBnHFToHB3K92wdu2y+fqMuKRp7by2d8RHe1BHGA/OX+vlSnpYO4gAnbGQbs5DzAR8qNIpr8qZ8A7Ee7uXJR/eohqOWyxWPhxIJld5uTiKYBDbLxwEDeXCLJzcCjGRwX3NJNIKhWWQeQYhGnCf2yWOZNwSr4wqLIL/BJzy+yHmw52ZsmMr2YUm96MPhDj59hyjfLHQQBAnYP6mAiUKd3/DSYV2eCpbvdTsnfdZCDVWxGfZSTjDMwO2cUBM8+HWRAiqYTGUm1DlzEu6g6SxD+XM5KCxrhT8zJo7rzaH9YlU1hxx/GT5LDynhYelttD/WVZL+mVa6A//bORAS8aPm01tmJtJtmx36Tm8nVYZaZyUEIvxrdNIqEVPnwHf2Ridl5OLHR7fh2XftrZEy7w3uvLiLEibemsLX9WySErUy+OOoE5CCHqA80vHlzA8cPLbA8PyCGfwluYP8HsVBGtSF5ZZSD4T61BjoQ0T2J00fnGi8o7P0RlxPhA0Sq5jb1KDMPK5E8Fokx8Da6YT5yEGHTAo1/UkQS7YIFUf0KZWhTfYnKHA9aIizTOlKlIzTinZt+y7XjgfvtHdttxEUazcRKF1/vInEYTKeH/ufYzB7xhHjcZVppMI0Zaz4DNQiC7pu769e4dM/0+eaA1tOTTRzhbw7dcVlrzOjWAmgJcTSBPtcNwtQ9RWHAIEMKz5x8XzJootU2dzF3LAPmU6AWTFSO"
    }
  }
}
