{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "ghcr-credentials",
    "namespace": "the-machine"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "ghcr-credentials",
        "namespace": "the-machine"
      },
      "type": "kubernetes.io/dockerconfigjson"
    },
    "encryptedData": {
      ".dockerconfigjson": "AgA+vGbaRoemXGd3OBZ8fYOqSeiBsvftQO0S6u6YOgH05JQWEsbcHRS4tUbBlX7H1QCLn87l5e0RHL0lETGRQZCzBmTIzDTdwPJKtbZbFA3KlwXqe0CtnxYCZuRtguHovn9fHvthW4QSey23UTVD1weDBqwiYLanVW6zuDY50hE6VpAovEtsbW5cLKyrcTpQewAuv0rXflTha3x3qZ+8583AXdmHXDsWQJAo9o1wrhCUJAWD+1ltdU/fECCpi1vI3eC9QzrdEODbO7BLxldLEqWeVKO6W+yEXFpcGKZs7liQ/LsDyF+M4rYYGaLqcARw6PtmfyWAOed9L4R/n0fMZBwTSXmzYlvwwenzL8frHcXSQqBpXPkTmCVjHsf1zRgZpLx8PMvH97VddO0p0HGr1s9qGGZhvLvagVfySmiKuqTm8J/J4xw9I+NMgs9VZLJXUtEpktNF7BVLtQaX5+Qssr616TogI76zlNX2nT+eR+QMgLrRQQMZP5N0IozGY2Ben3sBOVbz5oR1mCtHf5T0zw27eZGi+PfluFSE9W6C1hJD5bXjbJLoaivzM/d6vlYJOSyCUygo59e8sYx7MqDGkoV1WchArtL0/cvl96Pf7+4YFh9N7ujvSvKAR2/DoDgYtx6Ef2idYsFW0BG03FdUkVuyukskqxB7IBgUbHSM5NOwcnM/M3EWx6zyTV36pL41bHZ+7X52/Nz80AwcQLo2gI2V37fLxJwMi02Yu2GSLOXEe0LId6fiDMldoO9kSTEgEmp2i8dbBE1Wi/rAnPMw8YDZrAG8O5V2YE1LHNIFgw=="
    }
  }
}
