{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "ghcr-credentials",
    "namespace": "the-machine"
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "ghcr-credentials",
        "namespace": "the-machine"
      },
      "type": "kubernetes.io/dockerconfigjson"
    },
    "encryptedData": {
      ".dockerconfigjson": "AgAIsiTwaixNHZcYqe+fe9poasoXulFiR7ySM7g3GGh/zaVD+7BIsvbc+OajjMBs9+DMrnst8mAeJ/QE8ykBZ05YfuvZlqAizynfm0WzL0fngLroG2NIgQlJ68FbpqpmLJUc7aiVv40kApJfppgzaxnzh1y2aG051Nz4GRUa+iAGV7bvgRyBlMhf0H6L1YZrE4ZZsf+xJiDNM2GGHIeqZvP6/SLhWGgLHUQ6on2BQv2AAuDKVTMR9D5VcRPrBFv3kIbPf2TLG7zXrBWVrl5ct1dwtDmFCq/TdMfUoamdHZlr/kfxTumVSXbrE3lTV9rzgijzjUqKky7OpGZq6hInvGQlNghIMHX/B6Vl6lSwD0enORUMdJDqz3xWuaMJwiZfmKwtihQOJUa3RylMnDOEDOxQXE1SeQPDbDKbl1XRokLnfbZXd/KNtRuF8Ynz6uTbbA5/z5a+bSnBdM+50G1qoL68+Gl/5kW2jXqB4yCUye6+AlD3Knlhh7aULrSLtIPpa6t19Ud+FNAGSPyxSz2ReVUnq20/ZgTjgS3sA8Yi2h4I1J156mH5WKx1TdvFLRHzJU9VRbdDW7esxt9xpkbp+rIsIc8jRVixhOiJ+kQMvxVG318qWxn9zY+0u9L/BzOohlrFGFcYbkkJQK86lTceWz2asaAtxUAxrrnDEocMGb7IEr14XqhnDunD0Y/sA5gPe8THQz1vNPyt5NRGcCTigr4Rf3g7U+ukwNEeHN1HBO8jzVwNe6mvxQUJgLUOFiBum3FK6h3Sb5SabAKOcsnJl0pR4ZxaFz3miJHZGGl5OwZpmc7YVh4+txd03+rJsMwvrriQ"
    }
  }
}
