domain: gitresethard.life
clusterIssuer: letsencrypt-prod
# app specific
nginxingress:
  enabled: true
certmanager:
  enabled: true
whoami:
  enabled: true
githubUser: loeken
githubRepo: enso-homelab
externaldns:
  enabled: true