domain: loeken.xyz
clusterIssuer: letsencrypt-prod
clusterName: enso-homelab-prod
githubUser: loeken
githubRepo: enso-homelab-prod
globalReplicaCount: 0

# app specific
authelia:
  enabled: true
  filesystem:
    enabled: true
  ingress:
    enabled: true
  smtp:
    enabled: false
    host: mail.internetz.me
    port: 587
    sender: auth@internetz.me
    username: auth@internetz.me
  storageClassName: rook-ceph-block
  size: 100Mi
certmanager:
  enabled: true
externaldns:
  enabled: true
homeassistant:
  enabled: true
  ingress:
    enabled: true
  storageClass: rook-ceph-block
  useAuthelia: true
jellyfin:
  enabled: true
  cache:
    enabled: true
    size: 10Gi
    storageClass: rook-cephfs
  config:
    enabled: true
    size: 1Gi
    storageClass: rook-cephfs
  ingress:
    enabled: true
  useAuthelia: false
k10:
  enabled: true
  storageClassName: rook-ceph-block
  sidecar:
    enabled: false
nextcloud:
  enabled: true
  size: 10Gi
  storageClass: rook-ceph-block
  data:
    accessMode: ReadWriteOnce
    size: 500Gi
    storageClass: rook-ceph-block
  ingress:
    enabled: true
  securityContext:
    runAsNonRoot: false
    runAsUser: 1000
    runAsGroup: 1000
  smtp:
    domain: internetz.me
    host: mail.internetz.me
    port: 587
    sender: nextcloud@internetz.me
    username: nextcloud@internetz.me
  storageClass: rook-ceph-block
  useAuthelia: false
nginxingress:
  enabled: true
nzbget:
  enabled: true
  ingress:
    enabled: true
  config:
    size: 1Gi
    storageClass: rook-ceph-block
  downloads:
    size: 100Gi
    storageClass: local-path
  useAuthelia: false
observability:
  enabled: true
  grafana:
    storageClassName: rook-ceph-block
    size: 10Gi
  prometheus:
    storageClassName: rook-ceph-block
    size: 10Gi
  alertmanager:
    storageClassName: rook-ceph-block
    size: 2Gi
  loki:
    storageClassName: rook-ceph-block
    size: 10Gi
  useAuthelia: true
rookceph:
  enabled: true
  monitoring: true
rookcephcluster:
  enabled: true
  monitoring: true
  createPrometheusRules: true
sharedmedia:
  enabled: true
  size: 100Gi
  storageClass: rook-cephfs
vaultwarden:
  enabled: true
  useAuthelia: true
  ingress:
    enabled: true
  storageClassName: rook-ceph-block
  size: 1Gi
  pg:
    storageClassName: rook-ceph-block
    size: 1Gi
whoami:
  enabled: true
uptimekuma:
  enabled: true
  storageClassName: rook-ceph-block
  size: 5Gi