domain: loeken.xyz
clusterIssuer: letsencrypt-prod
clusterName: enso-homelab-prod
githubUser: loeken
githubRepo: enso-homelab-prod
globalReplicaCount: 0

# app specific
authelia:
  enabled: true
  filesystem:
    enabled: true
  ingress:
    enabled: true
  smtp:
    enabled: false
    host: mail.internetz.me
    port: 587
    sender: auth@internetz.me
    username: auth@internetz.me
  storageClassName: rook-ceph-block
  size: 100Mi
certmanager:
  enabled: true
externaldns:
  enabled: true
k10:
  enabled: true
  storageClassName: rook-ceph-block
  sidecar:
    enabled: false
nextcloud:
  enabled: true
  size: 10Gi
  storageClass: rook-ceph-block
  data:
    accessMode: ReadWriteOnce
    size: 500Gi
    storageClass: rook-ceph-block
  ingress:
    nginx:
      enabled: true
  securityContext:
    runAsNonRoot: false
    runAsUser: 1000
    runAsGroup: 1000
  smtp:
    domain: internetz.me
    host: mail.internetz.me
    port: 587
    sender: nextcloud@internetz.me
    username: nextcloud@internetz.me
  storageClass: rook-ceph-block
  useAuthelia: false
nginxingress:
  enabled: true
observability:
  enabled: true
  grafana:
    storageClassName: rook-ceph-block
    size: 10Gi
  prometheus:
    storageClassName: rook-ceph-block
    size: 10Gi
  alertmanager:
    storageClassName: rook-ceph-block
    size: 2Gi
  loki:
    storageClassName: rook-ceph-block
    size: 10Gi
rookceph:
  enabled: true
  monitoring: false
rookcephcluster:
  enabled: true
  monitoring: false
  createPrometheusRules: false
vaultwarden:
  enabled: true
  useAuthelia: true
  ingress:
    enabled: true
  storageClassName: rook-ceph-block
  size: 1Gi
  pg:
    storageClassName: rook-ceph-block
    size: 1Gi
whoami:
  enabled: true
