apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cloudflared
  namespace: argocd
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: cloudflared
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  source:
    repoURL: https://cloudflare.github.io/helm-charts
    chart: cloudflared
    targetRevision: 0.3.3
    helm:
      releaseName: cloudflared
      values: |
        tunnelId: "{{ .ValuesFromSecret.TUNNEL_ID }}"
        tunnelName: "{{ .ValuesFromSecret.TUNNEL_NAME }}"
        credentials:
          existingSecret: cloudflared-runtime-creds
        config: |
          tunnel: "{{ .ValuesFromSecret.TUNNEL_ID }}"
          credentials-file: /etc/cloudflared/creds.json
          ingress:
            - hostname: test.enso-homelab.dev
              service: http://nginx-ingress.nginx-ingress.svc.cluster.local:80
            - service: http_status:404