name: Proxmox Convert & Template

on:
  workflow_dispatch:
  issue_comment:
    types: [created]

jobs:
  run-proxmox-ansible:
    if: |
      github.event_name == 'workflow_dispatch' ||
      (github.event.issue.pull_request == null && contains(github.event.comment.body, '/convert-to-proxmox'))
    runs-on: ubuntu-latest

    container:
      image: loeken/enso-devcontainer:latest
      options: --user 1000:1000
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key inside container
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" | base64 -d > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          echo "SSH key installed"
          ls -l ~/.ssh

      - name: Run Ansible Playbook
        run: |
          ANSIBLE_HOST_KEY_CHECKING=False ansible-playbook \
            -i ./deploy/ansible/proxmox/inventory \
            ./deploy/ansible/proxmox/base.yml
