name: Validate Required Secrets

on:
  workflow_call:
    inputs: {}
    secrets:
      SSH_USERNAME: {}
      SSH_SERVER_ADDRESS: {}
      SSH_INTERNAL_ADDRESS: {}
      SSH_SERVER_PORT: {}
      SSH_PRIVATE_KEY: {}
      TF_TOKEN_app_terraform_io: {}
      HOSTNAME: {}
      TF_CLOUD_ORGANIZATION: {}
      KUBECONFIG: {}
      PAT_GITHUB_TOKEN: {}
      RENOVATE_TOKEN: {}
      DEPLOYMENT_TYPE: {}
      # Add any other secrets you want to validate
  workflow_dispatch: {}
jobs:
  validate-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Validate required secrets
        run: .github/scripts/validate-secrets.sh
        shell: bash
        env:
          SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
          SSH_SERVER_ADDRESS: ${{ secrets.SSH_SERVER_ADDRESS }}
          SSH_INTERNAL_ADDRESS: ${{ secrets.SSH_INTERNAL_ADDRESS }}
          SSH_SERVER_PORT: ${{ secrets.SSH_SERVER_PORT }}
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          TF_TOKEN_app_terraform_io: ${{ secrets.TF_TOKEN_app_terraform_io }}
          HOSTNAME: ${{ secrets.HOSTNAME }}
          TF_CLOUD_ORGANIZATION: ${{ secrets.TF_CLOUD_ORGANIZATION }}
          PAT_GITHUB_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
          RENOVATE_TOKEN: ${{ secrets.RENOVATE_TOKEN }}
          DEPLOYMENT_TYPE: ${{ secrets.DEPLOYMENT_TYPE }}

      - name: Trigger Proxmox install workflow if deployment type is proxmox-single
        if: env.DEPLOYMENT_TYPE == 'proxmox-single'
        env:
          GH_TOKEN: ${{ secrets.PAT_GITHUB_TOKEN }}
        run: |
          echo "DEPLOYMENT_TYPE is proxmox-single, triggering install_proxmox.yml workflow..."
          gh workflow run install_proxmox.yml